# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.cow import ImplicitAPI
import math
from ccxt.base.types import Any, Balances, Int, Market, Order, OrderSide, OrderType, Str, Trade
from typing import List
from ccxt.base.errors import ExchangeError
from ccxt.base.errors import AuthenticationError
from ccxt.base.errors import ArgumentsRequired
from ccxt.base.errors import BadRequest
from ccxt.base.errors import BadSymbol
from ccxt.base.errors import InsufficientFunds
from ccxt.base.errors import InvalidOrder
from ccxt.base.errors import OrderNotFound
from ccxt.base.errors import NotSupported
from ccxt.base.decimal_to_precision import TICK_SIZE
from ccxt.base.precise import Precise


class cow(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(cow, self).describe(), {
            'id': 'cow',
            'name': 'CoW Protocol',
            'countries': [],
            'rateLimit': 500,
            'has': {
                'spot': True,
                'fetchMarkets': True,
                'fetchBalance': True,
                'createOrder': True,      # POST /orders(signed body)
                'cancelOrder': True,      # DELETE /orders(signed body)
                'cancelAllOrders': True,  # cancel multiple open orders
                'fetchOrder': True,       # GET /orders/{uid}
                'fetchOrders': True,      # GET /account/{owner}/orders
                'fetchOpenOrders': True,
                'fetchClosedOrders': True,
                'fetchCanceledOrders': True,
                'fetchMyTrades': True,
                'fetchTicker': False,
                'fetchTickers': False,
                'fetchOrderBook': False,
                'fetchTrades': False,
                'fetchCurrencies': False,
            },
            'features': {
                'spot': {
                    'sandbox': True,  # barn environment serves
                    'createOrder': {
                        'marginMode': False,
                        'triggerPrice': False,
                        'triggerDirection': False,
                        'triggerPriceType': None,
                        'stopLossPrice': False,
                        'takeProfitPrice': False,
                        'attachedStopLossTakeProfit': None,
                        'timeInForce': {
                            'GTC': True,  # Good Till Cancelled(default)
                            'IOC': True,  # Immediate Or Cancel
                            'FOK': True,  # Fill Or Kill
                            'PO': False,  # Post Only
                            'GTD': False,  # Good Till Date
                        },
                        'hedged': False,
                        'trailing': False,
                        'leverage': False,
                        'marketBuyByCost': False,
                        'marketBuyRequiresPrice': False,
                        'selfTradePrevention': False,
                        'iceberg': False,
                    },
                    'createOrders': None,
                    'fetchMyTrades': {
                        'marginMode': False,
                        'limit': 1000,  # API default limit
                        'daysBack': None,
                        'untilDays': None,
                        'symbolRequired': False,
                    },
                    'fetchOrder': {
                        'marginMode': False,
                        'trigger': False,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchOpenOrders': {
                        'marginMode': False,
                        'limit': 1000,
                        'trigger': False,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchOrders': {
                        'marginMode': False,
                        'limit': 1000,
                        'daysBack': None,
                        'untilDays': None,
                        'trigger': False,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchClosedOrders': {
                        'marginMode': False,
                        'limit': 1000,
                        'daysBack': None,
                        'daysBackCanceled': None,
                        'untilDays': None,
                        'trigger': False,
                        'trailing': False,
                        'symbolRequired': False,
                    },
                    'fetchOHLCV': {
                        'limit': None,
                    },
                },
            },
            'requiredCredentials': {
                'apiKey': False,
                'secret': False,
                'uid': False,
                'login': False,
                'password': False,
                'twofa': False,
                'token': False,
                'walletAddress': True,
                'privateKey': True,
            },
            'urls': {
                'api': 'https://api.cow.fi',
                'www': 'https://cow.fi',
                'doc': 'https://docs.cow.fi/cow-protocol/reference/apis/orderbook',
            },
            'api': {
                'public': {
                    'get': {
                        'api/v1/orders/{uid}': 1,
                        'api/v1/trades': 1,
                        'api/v1/account/{owner}/orders': 1,
                    },
                    'post': {
                        'api/v1/quote': 12,
                        'api/v1/orders': 1,
                    },
                    'delete': {
                        'api/v1/orders': 1,
                    },
                },
            },
            'options': {
                'network': 'mainnet',
                'env': 'prod',
                'hosts': {
                    'prod': 'https://api.cow.fi',
                    'barn': 'https://barn.api.cow.fi',
                },
                'networkIds': {
                    'mainnet': 'mainnet',
                    'xdai': 'xdai',
                    'arbitrum_one': 'arbitrum-one',
                    'base': 'base',
                    'sepolia': 'sepolia',
                },
                'defaultQuoteTokens': ['USDC', 'USDT', 'DAI', 'WETH'],
                'walletAddress': None,
                'tokenListUrl': 'https://files.cow.fi/tokens/CowSwap.json',
                'chainIds': {
                    'mainnet': 1,
                    'xdai': 100,
                    'arbitrum_one': 42161,
                    'base': 8453,
                    'sepolia': 11155111,
                },
                'verifyingContracts': {
                    'mainnet': '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                    'xdai': '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                    'arbitrum_one': '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                    'base': '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                    'sepolia': '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                },
                'vaultRelayers': {
                    'mainnet': '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                    'xdai': '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                    'arbitrum_one': '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                    'base': '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                    'sepolia': '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                },
                'rpcUrls': {
                    'mainnet': 'https://eth.llamarpc.com',
                    'xdai': 'https://rpc.gnosischain.com',
                    'arbitrum_one': 'https://arb1.arbitrum.io/rpc',
                    'base': 'https://mainnet.base.org',
                    'sepolia': 'https://rpc.sepolia.org',
                },
                'autoApprove': True,  # Automatically approve VaultRelayer if allowance is insufficient
                'cancellationVerifyingContract': '0x0000000000000000000000000000000000000000',
                'defaultValidFor': 30,
                'defaultAppData': '0x0000000000000000000000000000000000000000000000000000000000000000',
                'defaultSigningScheme': 'ethsign',
                'tokenBalances': {
                    'erc20': 0,
                    'external': 1,
                    'internal': 2,
                },
                'orderKinds': {
                    'sell': 0,
                    'buy': 1,
                },
                'waitForOrder': {
                    'pollingDelay': 2000,
                    'timeout': 60000,
                    'statuses': ['closed', 'canceled', 'expired', 'rejected'],
                },
            },
            'precisionMode': TICK_SIZE,
            'fees': {
                'trading': {
                    'tierBased': False,
                    'percentage': True,
                    'maker': self.parse_number('0'),
                    'taker': self.parse_number('0'),
                },
            },
        })

    def resolve_orderbook_base_url(self, network: Str = None, env: Str = None) -> str:
        defaultNetwork = self.safe_string(self.options, 'network', 'mainnet')
        selectedNetwork = defaultNetwork if (network is None) else network
        defaultEnv = self.safe_string(self.options, 'env', 'prod')
        selectedEnv = defaultEnv if (env is None) else env
        networkMap = self.safe_value(self.options, 'networkIds', {})
        networkId = self.safe_string(networkMap, selectedNetwork)
        if networkId is None:
            raise ExchangeError(self.id + ' resolveOrderbookBaseUrl() unsupported network: ' + selectedNetwork)
        hosts = self.safe_value(self.options, 'hosts', {})
        host = self.safe_string(hosts, selectedEnv)
        if host is None:
            raise ExchangeError(self.id + ' resolveOrderbookBaseUrl() unsupported environment: ' + selectedEnv)
        return host + '/' + networkId + '/api/v1'

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        paramsWithoutPath = self.omit(params, self.extract_params(path))
        network = self.safe_string_2(paramsWithoutPath, 'network', 'chainId')
        env = self.safe_string(paramsWithoutPath, 'env')
        query = self.omit(paramsWithoutPath, ['network', 'chainId', 'env'])
        baseUrl = self.resolve_orderbook_base_url(network, env)
        pathWithParams = self.implode_params(path, params)
        versionPrefix = 'api/v1/'
        if pathWithParams.find(versionPrefix) == 0:
            pathWithParams = pathWithParams.replace(versionPrefix, '')
        url = baseUrl
        if len(pathWithParams) > 0:
            url = url + '/' + pathWithParams
        if (method == 'GET') or (method == 'DELETE'):
            if not self.is_empty(query):
                url = url + '?' + self.urlencode(query)
        else:
            if not self.is_empty(query):
                body = self.json(query)
            headers = self.extend({}, headers)
            headers['Content-Type'] = 'application/json'
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    def fetch_markets(self, params={}) -> List[Market]:
        """
        retrieves data on all markets for CoW Protocol

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.tokenListUrl]: override the default token list URL
        :param Array [params.tokens]: manually provide a token list instead of fetching
        :param Array [params.quoteSymbols]: override default quote symbols(USDC, USDT, DAI, WETH)
        :param int [params.chainId]: override the chain ID for filtering tokens
        :returns dict[]: an array of objects representing market data
        """
        parameters = self.extend({}, params)
        tokenListUrl = self.safe_string(parameters, 'tokenListUrl', self.safe_string(self.options, 'tokenListUrl', 'https://files.cow.fi/tokens/CowSwap.json'))
        overrideTokens = self.safe_list(parameters, 'tokens')
        overrideQuotes = self.safe_value(parameters, 'quoteSymbols')
        overrideChainId = self.safe_integer(parameters, 'chainId')
        tokenList: dict = None
        if overrideTokens is not None:
            tokenList = {'tokens': overrideTokens}
        else:
            tokenList = self.fetch(tokenListUrl, 'GET', None, None)
        tokens = self.safe_list(tokenList, 'tokens', [])
        targetChainId = self.get_chain_id_option() if (overrideChainId is None) else overrideChainId
        tokensBySymbol: dict = {}
        for i in range(0, len(tokens)):
            token = tokens[i]
            chainId = self.safe_integer(token, 'chainId')
            if (chainId is not None) and (chainId != targetChainId):
                continue
            symbol = self.safe_string_upper(token, 'symbol')
            if symbol is None:
                continue
            address = self.safe_string_lower(token, 'address')
            if not (symbol in tokensBySymbol):
                tokenRecord = self.extend({}, token)
                if address is not None:
                    tokenRecord['address'] = address
                tokensBySymbol[symbol] = tokenRecord
        defaultQuoteSymbols = self.safe_value(self.options, 'defaultQuoteTokens', ['USDC', 'USDT', 'DAI', 'WETH'])
        quoteSymbolsRaw = defaultQuoteSymbols if (overrideQuotes is None) else overrideQuotes
        quoteSymbols = []
        for i in range(0, len(quoteSymbolsRaw)):
            quote = quoteSymbolsRaw[i]
            if quote is not None:
                quoteSymbols.append(quote.upper())
        marketSymbols = list(tokensBySymbol.keys())
        markets = []
        for i in range(0, len(marketSymbols)):
            baseSymbol = marketSymbols[i]
            baseToken = tokensBySymbol[baseSymbol]
            baseAddress = self.safe_string_lower(baseToken, 'address')
            if baseAddress is None:
                baseAddress = baseSymbol.lower()
            baseDecimals = self.safe_integer(baseToken, 'decimals')
            amountPrecision = None if (baseDecimals is None) else self.parse_number(self.parse_precision(self.number_to_string(baseDecimals)))
            for j in range(0, len(quoteSymbols)):
                quoteSymbolRaw = quoteSymbols[j]
                if quoteSymbolRaw is None:
                    continue
                quoteSymbol = quoteSymbolRaw.upper()
                if baseSymbol == quoteSymbol:
                    continue
                quoteToken = self.safe_value(tokensBySymbol, quoteSymbol)
                if quoteToken is None:
                    continue
                quoteAddress = self.safe_string_lower(quoteToken, 'address')
                if quoteAddress is None:
                    quoteAddress = quoteSymbol.lower()
                baseCode = self.safe_currency_code(baseSymbol)
                quoteCode = self.safe_currency_code(quoteSymbol)
                symbol = baseCode + '/' + quoteCode
                marketId = baseAddress + '-' + quoteAddress
                markets.append(self.safe_market_structure({
                    'id': marketId,
                    'uppercaseId': None,
                    'symbol': symbol,
                    'base': baseCode,
                    'quote': quoteCode,
                    'baseId': baseAddress,
                    'quoteId': quoteAddress,
                    'type': 'spot',
                    'spot': True,
                    'margin': False,
                    'swap': False,
                    'future': False,
                    'option': False,
                    'taker': self.parse_number('0'),
                    'maker': self.parse_number('0'),
                    'contract': False,
                    'linear': None,
                    'inverse': None,
                    'contractSize': None,
                    'expiry': None,
                    'expiryDatetime': None,
                    'strike': None,
                    'optionType': None,
                    'settle': None,
                    'settleId': None,
                    'active': True,
                    'limits': {
                        'amount': {
                            'min': None,
                            'max': None,
                        },
                        'price': {
                            'min': None,
                            'max': None,
                        },
                        'cost': {
                            'min': None,
                            'max': None,
                        },
                        'leverage': {
                            'min': None,
                            'max': None,
                        },
                    },
                    'precision': {
                        'amount': amountPrecision,
                        'price': None,
                    },
                    'info': {
                        'base': baseToken,
                        'quote': quoteToken,
                    },
                    'created': None,
                }))
        return markets

    def parse_trade(self, trade: dict, market: Market = None) -> Trade:
        sellToken = self.safe_string_lower(trade, 'sellToken')
        buyToken = self.safe_string_lower(trade, 'buyToken')
        resolvedMarket = market
        if (sellToken is not None) and (buyToken is not None):
            marketId = sellToken + '-' + buyToken
            resolvedMarket = self.safe_market(marketId, resolvedMarket, None, 'spot')
        resolvedMarket = self.safe_market(None, resolvedMarket, None, 'spot')
        symbol = self.safe_string(resolvedMarket, 'symbol')
        marketInfo = self.safe_value(resolvedMarket, 'info', {})
        baseInfo = self.safe_value(marketInfo, 'base', {})
        quoteInfo = self.safe_value(marketInfo, 'quote', {})
        baseDecimals = self.safe_string(baseInfo, 'decimals')
        quoteDecimals = self.safe_string(quoteInfo, 'decimals')
        sellAmountRaw = self.safe_string(trade, 'sellAmount')
        buyAmountRaw = self.safe_string(trade, 'buyAmount')
        feeAmountRaw = self.safe_string(trade, 'feeAmount')
        kind = self.safe_string_lower(trade, 'kind')
        timestamp = self.safe_integer(trade, 'timestamp')
        orderUid = self.safe_string(trade, 'orderUid')
        tradeId = self.safe_string(trade, 'tradeUid')
        executedSellRaw = self.safe_string(trade, 'executedSellAmount', sellAmountRaw)
        executedBuyRaw = self.safe_string(trade, 'executedBuyAmount', buyAmountRaw)
        baseId = self.safe_string_lower(resolvedMarket, 'baseId')
        quoteId = self.safe_string_lower(resolvedMarket, 'quoteId')
        side = None
        amountRaw = None
        costRaw = None
        if baseId == sellToken:
            side = 'sell'
            amountRaw = executedSellRaw
            costRaw = executedBuyRaw
        elif baseId == buyToken:
            side = 'buy'
            amountRaw = executedBuyRaw
            costRaw = executedSellRaw
        elif kind is not None:
            if kind == 'buy':
                side = 'buy'
            elif kind == 'sell':
                side = 'sell'
            amountRaw = executedSellRaw if (side == 'sell') else executedBuyRaw
            costRaw = executedBuyRaw if (side == 'sell') else executedSellRaw
        else:
            amountRaw = executedSellRaw
            costRaw = executedBuyRaw
        amountString = self.convert_token_amount(amountRaw, baseDecimals)
        costString = self.convert_token_amount(costRaw, quoteDecimals)
        price = None
        if (amountString is not None) and (costString is not None) and (not Precise.string_eq(amountString, '0')):
            price = self.parse_number(Precise.string_div(costString, amountString))
        amount = self.parse_number(amountString)
        cost = self.parse_number(costString)
        fee = None
        if feeAmountRaw is not None:
            feeCurrencyId = self.safe_string_lower(trade, 'feeToken')
            if feeCurrencyId is None:
                feeCurrencyId = sellToken
            feeCurrencyCode = None
            if feeCurrencyId == baseId:
                feeCurrencyCode = resolvedMarket['base']
            elif feeCurrencyId == quoteId:
                feeCurrencyCode = resolvedMarket['quote']
            else:
                feeCurrencyCode = self.safe_currency_code(feeCurrencyId)
            feeDecimals = baseDecimals if (feeCurrencyId == baseId) else quoteDecimals
            feeCost = self.parse_number(self.convert_token_amount(feeAmountRaw, feeDecimals))
            fee = {
                'cost': feeCost,
                'currency': feeCurrencyCode,
            }
        takerOrMaker = None
        return self.safe_trade({
            'info': trade,
            'id': tradeId,
            'order': orderUid,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'symbol': symbol,
            'type': None,
            'side': side,
            'price': price,
            'amount': amount,
            'cost': cost,
            'takerOrMaker': takerOrMaker,
            'fee': fee,
        }, resolvedMarket)

    def parse_order_status(self, status: Str):
        statuses: dict = {
            'open': 'open',
            'pending': 'open',
            'pending-solver-submission': 'open',
            'presignatureAwaiting': 'open',
            'presignaturePending': 'open',
            'fulfilled': 'closed',
            'expired': 'expired',
            'solved': 'closed',
            'cancelled': 'canceled',
            'canceled': 'canceled',
            'retracted': 'canceled',
            'failed': 'rejected',
        }
        return self.safe_string(statuses, status, status)

    def convert_token_amount(self, amount: Str, decimals: Str):
        if (amount is None) or (decimals is None):
            return None
        decimalsString = self.number_to_string(decimals)
        precision = self.parse_precision(decimalsString)
        return Precise.string_mul(amount, precision)

    def parse_order(self, order: dict, market: Market = None) -> Order:
        sellToken = self.safe_string_lower(order, 'sellToken')
        buyToken = self.safe_string_lower(order, 'buyToken')
        kind = self.safe_string_lower(order, 'kind')
        side = None
        if kind is not None:
            if kind == 'sell':
                side = 'sell'
            elif kind == 'buy':
                side = 'buy'
        resolvedMarket: Market = market
        if resolvedMarket is None:
            if (sellToken is not None) and (buyToken is not None):
                directId = sellToken + '-' + buyToken
                inverseId = buyToken + '-' + sellToken
                directMarket = self.safe_value(self.markets_by_id, directId)
                inverseMarket = self.safe_value(self.markets_by_id, inverseId)
                if (side == 'sell') and (directMarket is not None):
                    resolvedMarket = directMarket
                elif (side == 'buy') and (inverseMarket is not None):
                    resolvedMarket = inverseMarket
                elif directMarket is not None:
                    resolvedMarket = directMarket
                elif inverseMarket is not None:
                    resolvedMarket = inverseMarket
        resolvedMarket = self.safe_market(None, resolvedMarket, None, 'spot')
        symbol = self.safe_string(resolvedMarket, 'symbol')
        baseId = self.safe_string(resolvedMarket, 'baseId')
        quoteId = self.safe_string(resolvedMarket, 'quoteId')
        baseCurrency = self.safe_string(resolvedMarket, 'base')
        quoteCurrency = self.safe_string(resolvedMarket, 'quote')
        if side is None:
            if (resolvedMarket is not None) and (sellToken is not None) and (buyToken is not None):
                if (baseId == sellToken) and (quoteId == buyToken):
                    side = 'sell'
                elif (baseId == buyToken) and (quoteId == sellToken):
                    side = 'buy'
        marketInfo = self.safe_value(resolvedMarket, 'info', {})
        infoBase = self.safe_value(marketInfo, 'base', {})
        infoQuote = self.safe_value(marketInfo, 'quote', {})
        baseDecimals = self.safe_string(infoBase, 'decimals')
        quoteDecimals = self.safe_string(infoQuote, 'decimals')
        sellAmountRaw = self.safe_string(order, 'sellAmount')
        buyAmountRaw = self.safe_string(order, 'buyAmount')
        executedSellRaw = self.safe_string(order, 'executedSellAmount')
        executedBuyRaw = self.safe_string(order, 'executedBuyAmount')
        amountRaw = None
        filledRaw = None
        costRaw = None
        baseDecimalsUsed = baseDecimals
        quoteDecimalsUsed = quoteDecimals
        if side == 'sell':
            amountRaw = sellAmountRaw
            filledRaw = executedSellRaw
            costRaw = executedBuyRaw
        elif side == 'buy':
            amountRaw = buyAmountRaw
            filledRaw = executedBuyRaw
            costRaw = executedSellRaw
        else:
            amountRaw = sellAmountRaw
            filledRaw = executedSellRaw
            costRaw = executedBuyRaw
            if (baseId == buyToken) and (quoteId == sellToken):
                baseDecimalsUsed = quoteDecimals
                quoteDecimalsUsed = baseDecimals
        amount = None
        filled = None
        cost = None
        remaining = None
        costString = None
        amountString = self.convert_token_amount(amountRaw, baseDecimalsUsed)
        filledString = self.convert_token_amount(filledRaw, baseDecimalsUsed)
        costString = self.convert_token_amount(costRaw, quoteDecimalsUsed)
        if amountString is not None:
            amount = self.parse_number(amountString)
        if filledString is not None:
            filled = self.parse_number(filledString)
        if amountRaw is not None and filledRaw is not None:
            remainingRaw = Precise.string_sub(amountRaw, filledRaw)
            remainingString = self.convert_token_amount(remainingRaw, baseDecimalsUsed)
            if remainingString is not None:
                remaining = self.parse_number(remainingString)
        if costString is not None:
            cost = self.parse_number(costString)
        price = None
        if (filledString is not None) and (costString is not None) and (not Precise.string_eq(filledString, '0')):
            price = self.parse_number(Precise.string_div(costString, filledString))
        feeAmountRaw = self.safe_string(order, 'feeAmount')
        fee = None
        if feeAmountRaw is not None:
            feeDecimals = baseDecimalsUsed
            feeCurrency = baseCurrency
            if side == 'buy':
                feeDecimals = quoteDecimalsUsed
                feeCurrency = quoteCurrency
            feeAmountString = self.convert_token_amount(feeAmountRaw, feeDecimals)
            if feeAmountString is not None:
                fee = {
                    'currency': feeCurrency,
                    'cost': self.parse_number(feeAmountString),
                }
        statusRaw = self.safe_string(order, 'status')
        status = self.parse_order_status(statusRaw)
        timestamp = self.parse8601(self.safe_string_2(order, 'creationDate', 'creationTime'))
        if timestamp is None:
            timestamp = self.safe_integer_product(order, 'creationTime', 1000)
        validTo = self.safe_integer(order, 'validTo')
        expiry = (validTo * 1000) if (validTo is not None) else None
        orderType = None
        postOnly = None
        timeInForce = None
        clientOrderId = self.safe_string(order, 'appData')
        triggerPrice = None
        average = price
        lastTradeTimestamp = self.parse8601(self.safe_string(order, 'executionTime'))
        if lastTradeTimestamp is None:
            lastTradeTimestamp = self.safe_integer_product(order, 'executionTime', 1000)
        result = {
            'info': order,
            'id': self.safe_string(order, 'uid'),
            'clientOrderId': clientOrderId,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'lastTradeTimestamp': lastTradeTimestamp,
            'symbol': symbol,
            'type': orderType,
            'timeInForce': timeInForce,
            'postOnly': postOnly,
            'side': side,
            'price': price,
            'stopPrice': triggerPrice,
            'average': average,
            'cost': cost,
            'amount': amount,
            'filled': filled,
            'remaining': remaining,
            'status': status,
            'fee': fee,
            'triggerPrice': triggerPrice,
            'expiry': expiry,
        }
        return self.safe_order(result, resolvedMarket)

    def fetch_order(self, id: Str, symbol: Str = None, params={}) -> Order:
        """
        fetches information on an order made by the user

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str id: order id(UID)
        :param str symbol: unified symbol of the market the order was made in
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: An [order structure](https://docs.ccxt.com/#/?id=order-structure)
        """
        self.load_markets()
        request = {
            'uid': id,
        }
        response = self.publicGetApiV1OrdersUid(self.extend(request, params))
        order = self.safe_dict(response, 'order', response)
        market = None
        if symbol is not None:
            market = self.market(symbol)
        return self.parse_order(order, market)

    def fetch_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        """
        fetches information on multiple orders made by the user

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str symbol: unified market symbol of the market orders were made in
        :param int [since]: the earliest time in ms to fetch orders for
        :param int [limit]: the maximum number of order structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.owner]: the wallet address to fetch orders for
        :returns Order[]: a list of [order structures](https://docs.ccxt.com/#/?id=order-structure)
        """
        self.load_markets()
        market: Market = None
        if symbol is not None:
            market = self.market(symbol)
        owner: Str = None
        owner, params = self.ensure_owner_address(params)
        request: dict = {
            'owner': owner,
        }
        if limit is not None:
            request['limit'] = limit
        response = self.publicGetApiV1AccountOwnerOrders(self.extend(request, params))
        rawOrders = self.safe_list(response, 'orders', response)
        parsedOrders = self.parse_orders(rawOrders, market, since, limit)
        return self.filter_by_symbol_since_limit(parsedOrders, symbol, since, limit)

    def fetch_open_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        """
        fetch all unfilled currently open orders

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str symbol: unified market symbol
        :param int [since]: the earliest time in ms to fetch open orders for
        :param int [limit]: the maximum number of open order structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.owner]: the wallet address to fetch orders for
        :returns Order[]: a list of [order structures](https://docs.ccxt.com/#/?id=order-structure)
        """
        orders = self.fetch_orders(symbol, since, limit, params)
        return self.filter_by(orders, 'status', 'open')

    def fetch_closed_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        """
        fetches information on multiple closed orders made by the user

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str symbol: unified market symbol of the market orders were made in
        :param int [since]: the earliest time in ms to fetch orders for
        :param int [limit]: the maximum number of order structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.owner]: the wallet address to fetch orders for
        :returns Order[]: a list of [order structures](https://docs.ccxt.com/#/?id=order-structure)
        """
        orders = self.fetch_orders(symbol, since, limit, params)
        return self.filter_by(orders, 'status', 'closed')

    def fetch_canceled_orders(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Order]:
        """
        fetches information on multiple canceled orders made by the user

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str symbol: unified market symbol of the market orders were made in
        :param int [since]: the earliest time in ms to fetch orders for
        :param int [limit]: the maximum number of order structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.owner]: the wallet address to fetch orders for
        :returns Order[]: a list of [order structures](https://docs.ccxt.com/#/?id=order-structure)
        """
        orders = self.fetch_orders(symbol, since, limit, params)
        return self.filter_by(orders, 'status', 'canceled')

    def fetch_balance(self, params={}) -> Balances:
        """
        query for balance and get the amount of funds available for trading or funds locked in orders
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.owner]: the wallet address to query balance for
        :returns dict: a [balance structure](https://docs.ccxt.com/#/?id=balance-structure)
        """
        self.load_markets()
        owner: Str = None
        owner, params = self.ensure_owner_address(params)
        ownerAddress = self.address_with0x_prefix(owner)
        result: dict = {
            'info': {},
            'timestamp': None,
            'datetime': None,
        }
        currencies: dict = {}
        marketValues = list(self.markets.values())
        for i in range(0, len(marketValues)):
            market = marketValues[i]
            baseCode = self.safe_string(market, 'base')
            baseId = self.safe_string_lower(market, 'baseId')
            marketInfo = self.safe_value(market, 'info', {})
            baseInfo = self.safe_value(marketInfo, 'base', {})
            decimals = self.safe_string(baseInfo, 'decimals')
            if (baseCode is not None) and (baseId is not None) and (decimals is not None):
                if not (baseCode in currencies):
                    currencies[baseCode] = {'id': baseId, 'decimals': decimals}
        currencyCodes = list(currencies.keys())
        for i in range(0, len(currencyCodes)):
            code = currencyCodes[i]
            currencyInfo = currencies[code]
            tokenAddress = self.safe_string(currencyInfo, 'id')
            decimals = self.safe_string(currencyInfo, 'decimals')
            try:
                balanceRaw = self.fetch_erc20_balance(tokenAddress, ownerAddress)
                balanceString = self.convert_token_amount(balanceRaw, decimals)
                balance = self.parse_number(balanceString)
                result[code] = {
                    'free': balance,
                    'used': 0,  # CoW doesn't lock funds, orders are intent-based
                    'total': balance,
                }
            except Exception as e:
                result[code] = {
                    'free': 0,
                    'used': 0,
                    'total': 0,
                }
        return self.safe_balance(result)

    def fetch_my_trades(self, symbol: Str = None, since: Int = None, limit: Int = None, params={}) -> List[Trade]:
        """
        fetch all trades made by the user

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str symbol: unified market symbol
        :param int [since]: the earliest time in ms to fetch trades for
        :param int [limit]: the maximum number of trades structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.owner]: the wallet address to fetch trades for
        :returns Trade[]: a list of [trade structures](https://docs.ccxt.com/#/?id=trade-structure)
        """
        self.load_markets()
        market: Market = None
        if symbol is not None:
            market = self.market(symbol)
        owner: Str = None
        owner, params = self.ensure_owner_address(params)
        request: dict = {
            'owner': owner,
        }
        if limit is not None:
            request['limit'] = limit
        if since is not None:
            request['minTimestamp'] = since
        response = self.publicGetApiV1Trades(self.extend(request, params))
        trades = self.parse_trades(response, market, since, limit)
        return self.filter_by_symbol_since_limit(trades, symbol, since, limit)

    def create_order(self, symbol: str, type: OrderType, side: OrderSide, amount: float, price: float = None, params={}) -> Order:
        """
        create a trade order on CoW Protocol

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str symbol: unified symbol of the market to create an order in
        :param str type: 'market' or 'limit'
        :param str side: 'buy' or 'sell'
        :param float amount: how much of currency you want to trade in units of base currency
        :param float [price]: the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param int [params.validFor]: order validity duration in seconds(default 30)
        :param int [params.validTo]: unix timestamp when the order expires
        :param bool [params.partiallyFillable]: whether the order can be partially filled(default False)
        :param str [params.appData]: app data for the order(32-byte hex string)
        :param str [params.receiver]: the address to receive the bought tokens(defaults to sender)
        :param str [params.from]: the address placing the order(defaults to walletAddress)
        :param dict [params.quoteRequest]: override parameters for the quote request
        :returns dict: an [order structure](https://docs.ccxt.com/#/?id=order-structure)
        """
        self.load_markets()
        market = self.market(symbol)
        self.check_required_credentials()
        if (self.privateKey is None) or (self.privateKey == ''):
            raise AuthenticationError(self.id + ' createOrder() requires exchange.privateKey to be set')
        owner: Str = None
        owner, params = self.ensure_owner_address(params)
        receiverParam = self.safe_string_lower(params, 'receiver', owner)
        fromParam = self.safe_string_lower(params, 'from', owner)
        params = self.omit(params, ['receiver', 'from'])
        defaultKind = 'sell' if (side == 'sell') else 'buy'
        kind = self.safe_string_lower(params, 'kind', defaultKind)
        if (type != 'limit') and (type != 'market'):
            raise NotSupported(self.id + ' createOrder() supports market and limit order types')
        if (type == 'limit') and (price is None):
            raise ArgumentsRequired(self.id + ' createOrder() requires a price argument for limit orders')
        marketInfo = self.safe_value(market, 'info', {})
        baseInfo = self.safe_value(marketInfo, 'base', {})
        quoteInfo = self.safe_value(marketInfo, 'quote', {})
        baseDecimals = self.safe_string(baseInfo, 'decimals')
        quoteDecimals = self.safe_string(quoteInfo, 'decimals')
        partiallyFillable = self.safe_bool(params, 'partiallyFillable', False)
        validFor = self.safe_integer(params, 'validFor', self.safe_integer(self.options, 'defaultValidFor', 30))
        currentSeconds = self.seconds()
        validTo = self.safe_integer(params, 'validTo', currentSeconds + validFor)
        appData = self.safe_string(params, 'appData', self.safe_string(self.options, 'defaultAppData'))
        quoteRequestOverrides = self.safe_dict(params, 'quoteRequest')
        params = self.omit(params, ['kind', 'partiallyFillable', 'validFor', 'validTo', 'appData', 'quoteRequest'])
        isSellOrder = (kind == 'sell')
        sellToken = self.safe_string_lower(market, 'baseId') if isSellOrder else self.safe_string_lower(market, 'quoteId')
        buyToken = self.safe_string_lower(market, 'quoteId') if isSellOrder else self.safe_string_lower(market, 'baseId')
        sellTokenDecimals = baseDecimals if isSellOrder else quoteDecimals
        buyTokenDecimals = quoteDecimals if isSellOrder else baseDecimals
        amountString = self.number_to_string(amount)
        sellAmountRaw: Str = None
        buyAmountRaw: Str = None
        if isSellOrder:
            sellAmountRaw = self.amount_to_token_amount(amountString, sellTokenDecimals)
        else:
            buyAmountRaw = self.amount_to_token_amount(amountString, buyTokenDecimals)
        receiverAddress = self.address_with0x_prefix(receiverParam)
        fromAddress = self.address_with0x_prefix(fromParam)
        quoteRequest: dict = self.extend({
            'sellToken': self.address_with0x_prefix(sellToken),
            'buyToken': self.address_with0x_prefix(buyToken),
            'receiver': receiverAddress,
            'from': fromAddress,
            'kind': kind,
            'validTo': validTo,
            'partiallyFillable': partiallyFillable,
            'sellTokenBalance': 'erc20',
            'buyTokenBalance': 'erc20',
        }, quoteRequestOverrides)
        if isSellOrder:
            quoteRequest['sellAmountBeforeFee'] = self.safe_string(quoteRequest, 'sellAmountBeforeFee', sellAmountRaw)
            if type == 'limit':
                priceString = self.number_to_string(price)
                costDecimal = Precise.string_mul(amountString, priceString)
                buyAmountRawLimit = self.amount_to_token_amount(costDecimal, buyTokenDecimals)
                quoteRequest['buyAmountAfterFee'] = self.safe_string(quoteRequest, 'buyAmountAfterFee', buyAmountRawLimit)
        else:
            quoteRequest['buyAmountAfterFee'] = self.safe_string(quoteRequest, 'buyAmountAfterFee', buyAmountRaw)
            if type == 'limit':
                priceString = self.number_to_string(price)
                costDecimal = Precise.string_mul(amountString, priceString)
                sellAmountRawLimit = self.amount_to_token_amount(costDecimal, sellTokenDecimals)
                quoteRequest['sellAmountBeforeFee'] = self.safe_string(quoteRequest, 'sellAmountBeforeFee', sellAmountRawLimit)
        quoteResponse = self.publicPostApiV1Quote(quoteRequest)
        quote = self.safe_dict(quoteResponse, 'quote', quoteResponse)
        orderBody: dict = {
            'sellToken': self.address_with0x_prefix(self.safe_string(quote, 'sellToken', sellToken)),
            'buyToken': self.address_with0x_prefix(self.safe_string(quote, 'buyToken', buyToken)),
            'receiver': self.address_with0x_prefix(self.safe_string(quote, 'receiver', receiverParam)),
            'sellAmount': self.safe_string(quote, 'sellAmount', sellAmountRaw),
            'buyAmount': self.safe_string(quote, 'buyAmount', self.safe_string(quoteRequest, 'buyAmountAfterFee')),
            'validTo': self.safe_integer(quote, 'validTo', validTo),
            'appData': self.safe_string(quote, 'appData', appData),
            'feeAmount': '0',  # CoW Protocol requires fee to be zero(fee is already included in sellAmount)
            'kind': self.safe_string_lower(quote, 'kind', kind),
            'partiallyFillable': self.safe_bool(quote, 'partiallyFillable', partiallyFillable),
            'sellTokenBalance': self.safe_string_lower(quote, 'sellTokenBalance', 'erc20'),
            'buyTokenBalance': self.safe_string_lower(quote, 'buyTokenBalance', 'erc20'),
        }
        signingScheme = self.safe_string_lower(quote, 'signingScheme', 'eip712')
        orderBody['signingScheme'] = signingScheme
        orderBody['signature'] = self.sign_order_payload(orderBody, signingScheme)
        signerAddr = self.derive_wallet_address_from_private_key()
        orderBody['from'] = self.address_with0x_prefix(signerAddr).lower()
        autoApprove = self.safe_bool(self.options, 'autoApprove', True)
        if autoApprove:
            sellTokenAddress = self.safe_string(orderBody, 'sellToken')
            if sellTokenAddress is not None:
                vaultRelayer = self.get_vault_relayer_option()
                sellAmount = self.safe_string(orderBody, 'sellAmount', '0')
                feeAmount = self.safe_string(orderBody, 'feeAmount', '0')
                requiredAmount = Precise.string_add(sellAmount, feeAmount)
                try:
                    currentAllowance = self.check_erc20_allowance(sellTokenAddress, self.hex_with0x_prefix(signerAddr), vaultRelayer)
                    if Precise.string_lt(currentAllowance, requiredAmount):
                        self.log('Insufficient allowance detected. Approving VaultRelayer...')
                        approvalResult = self.approve_erc20(sellTokenAddress, vaultRelayer)
                        self.log('Approval transaction:', approvalResult['txHash'])
                        self.sleep(5000)
                except Exception as e:
                    message = self.safe_string(e, 'message', self.json(e))
                    raise ExchangeError(self.id + ' createOrder() failed to ensure allowance: ' + message)
        response = self.publicPostApiV1Orders(orderBody)
        uid = self.safe_string_2(response, 'orderUid', 'uid')
        parsed = self.parse_order(self.extend({}, orderBody, {'uid': uid, 'info': response, 'status': 'open'}), market)
        return self.extend(parsed, {'info': response})

    def cancel_order(self, id: str, symbol: Str = None, params={}) -> Order:
        """
        cancels an open order

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str id: order id(UID)
        :param str symbol: unified symbol of the market the order was made in
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.signingScheme]: 'eip712' or 'ethsign'(default 'eip712')
        :returns dict: An [order structure](https://docs.ccxt.com/#/?id=order-structure)
        """
        self.load_markets()
        self.check_required_credentials()
        if (self.privateKey is None) or (self.privateKey == ''):
            raise AuthenticationError(self.id + ' cancelOrder() requires exchange.privateKey to be set')
        owner: Str = None
        owner, params = self.ensure_owner_address(params)
        signingScheme = self.safe_string_lower(params, 'signingScheme', 'eip712')
        params = self.omit(params, ['signingScheme'])
        orderUids = [id]
        requestBody: dict = {
            'orderUids': orderUids,
            'signature': self.sign_order_cancellation(orderUids, signingScheme),
            'signingScheme': signingScheme,
        }
        headers = {'Content-Type': 'application/json'}
        response = self.request('api/v1/orders', 'public', 'DELETE', params, headers, self.json(requestBody))
        market = self.market(symbol) if (symbol is not None) else None
        return self.parse_order({'uid': id, 'status': 'canceled', 'info': response, 'owner': owner}, market)

    def cancel_all_orders(self, symbol: Str = None, params={}) -> List[Order]:
        """
        cancel all open orders

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str symbol: unified market symbol, only orders in the market of self symbol are cancelled when symbol is not None
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.owner]: the wallet address to cancel orders for
        :param str [params.signingScheme]: 'eip712' or 'ethsign'(default 'eip712')
        :returns dict[]: a list of [order structures](https://docs.ccxt.com/#/?id=order-structure)
        """
        self.load_markets()
        openOrders = self.fetch_open_orders(symbol, None, None, params)
        if len(openOrders) == 0:
            return []
        results = []
        for i in range(0, len(openOrders)):
            order = openOrders[i]
            orderId = self.safe_string(order, 'id')
            if orderId is not None:
                try:
                    result = self.cancel_order(orderId, symbol, params)
                    results.append(result)
                except Exception as e:
                    results.append(self.extend(order, {'status': 'failed', 'info': e}))
        return results

    def ensure_owner_address(self, params: dict = {}) -> List[Any]:
        owner = self.safe_string_lower_2(params, 'owner', 'walletAddress')
        modifiedParams = self.omit(params, ['owner', 'walletAddress'])
        derivedOwner = self.derive_wallet_address_from_private_key()
        if owner is None:
            optionOwner = self.safe_string_lower(self.options, 'walletAddress')
            if optionOwner is not None:
                owner = optionOwner
            elif (self.walletAddress is not None) and (isinstance(self.walletAddress, str)) and (self.walletAddress != ''):
                owner = self.walletAddress.lower()
            elif derivedOwner is not None:
                owner = derivedOwner
        if (owner is not None) and not owner.startswith('0x'):
            owner = '0x' + owner
        if (derivedOwner is not None) and (owner is not None) and (owner.lower() != derivedOwner):
            raise AuthenticationError(self.id + ' walletAddress mismatch between provided owner and private key')
        if owner is None:
            raise ArgumentsRequired(self.id + ' requires a wallet address; set exchange.walletAddress, exchange.options["walletAddress"] or provide params["owner"]')
        return [owner.lower(), modifiedParams]

    def hex_with0x_prefix(self, value: Str) -> Str:
        if value is None:
            return value
        return value if value.startswith('0x') else ('0x' + value)

    def address_with0x_prefix(self, value: Str) -> Str:
        return self.hex_with0x_prefix(value)

    def normalize_private_key(self, privateKey: Str) -> Str:
        if privateKey is None:
            return privateKey
        return self.hex_with0x_prefix(privateKey)

    def derive_wallet_address_from_private_key(self) -> Str:
        normalizedKey = self.normalize_private_key(self.privateKey)
        if (normalizedKey is None) or (normalizedKey == ''):
            return None
        keyHex = self.remove0x_prefix(normalizedKey)
        if len(keyHex) != 64:
            raise AuthenticationError(self.id + ' privateKey must be a 32-byte hex string')
        privateKeyBytes = self.base16_to_binary(keyHex)
        publicKey = secp256k1.getPublicKey(privateKeyBytes, False)
        hashBytes = keccak(publicKey[1:])
        addressBytes = hashBytes[-20:]
        address = '0x' + self.binary_to_base16(addressBytes)
        return address.lower()

    def amount_to_token_amount(self, amountString: Str, decimals: Str) -> Str:
        if (amountString is None) or (decimals is None):
            return None
        decimalsString = self.number_to_string(decimals)
        precision = self.parse_precision(decimalsString)
        return Precise.string_div(amountString, precision)

    def get_chain_id_option(self):
        network = self.safe_string(self.options, 'network', 'mainnet')
        chains = self.safe_value(self.options, 'chainIds', {})
        chainId = self.safe_integer(chains, network)
        if chainId is None:
            raise ExchangeError(self.id + ' unsupported network ' + network + ' for chain id resolution')
        return chainId

    def get_verifying_contract_option(self):
        network = self.safe_string(self.options, 'network', 'mainnet')
        contracts = self.safe_value(self.options, 'verifyingContracts', {})
        verifyingContract = self.safe_string(contracts, network)
        if verifyingContract is None:
            raise ExchangeError(self.id + ' unsupported network ' + network + ' for verifying contract resolution')
        return self.hex_with0x_prefix(verifyingContract)

    def get_vault_relayer_option(self):
        network = self.safe_string(self.options, 'network', 'mainnet')
        relayers = self.safe_value(self.options, 'vaultRelayers', {})
        vaultRelayer = self.safe_string(relayers, network)
        if vaultRelayer is None:
            raise ExchangeError(self.id + ' unsupported network ' + network + ' for vault relayer resolution')
        return self.hex_with0x_prefix(vaultRelayer)

    def get_rpc_url_option(self):
        network = self.safe_string(self.options, 'network', 'mainnet')
        rpcUrls = self.safe_value(self.options, 'rpcUrls', {})
        return self.safe_string(rpcUrls, network)

    def fetch_erc20_balance(self, tokenAddress: Str, ownerAddress: Str):
        rpcUrl = self.get_rpc_url_option()
        if rpcUrl is None:
            raise ExchangeError(self.id + ' fetchERC20Balance() requires rpcUrls[' + self.options['network'] + '] to be configured')
        ownerPadded = self.remove0x_prefix(ownerAddress).rjust(64, '0')
        # ERC20 balanceOf(address) = 0x70a08231
        data = '0x70a08231' + ownerPadded
        request = {
            'jsonrpc': '2.0',
            'method': 'eth_call',
            'params': [
                {
                    'to': tokenAddress,
                    'data': data,
                },
                'latest',
            ],
            'id': 1,
        }
        response = self.fetch(rpcUrl, 'POST', {'Content-Type': 'application/json'}, self.json(request))
        result = self.safe_string(response, 'result', '0x0')
        errorResult = self.safe_value(response, 'error')
        if errorResult is not None:
            raise ExchangeError(self.id + ' fetchERC20Balance() RPC error: ' + self.json(errorResult))
        if result == '0x':
            return '0'
        hexValue = self.remove0x_prefix(result)
        if hexValue == '':
            return '0'
        return BigInt('0x' + str(hexValue))

    def check_erc20_allowance(self, tokenAddress: Str, ownerAddress: Str, spenderAddress: Str):
        rpcUrl = self.get_rpc_url_option()
        if rpcUrl is None:
            raise ExchangeError(self.id + ' checkERC20Allowance() requires rpcUrls[' + self.options['network'] + '] to be configured')
        ownerPadded = self.remove0x_prefix(ownerAddress).rjust(64, '0')
        spenderPadded = self.remove0x_prefix(spenderAddress).rjust(64, '0')
        data = '0xdd62ed3e' + ownerPadded + spenderPadded
        request = {
            'jsonrpc': '2.0',
            'method': 'eth_call',
            'params': [
                {
                    'to': tokenAddress,
                    'data': data,
                },
                'latest',
            ],
            'id': 1,
        }
        response = self.fetch(rpcUrl, 'POST', {'Content-Type': 'application/json'}, self.json(request))
        result = self.safe_string(response, 'result', '0')
        if result == '0':
            errorResult = self.safe_value(response, 'error')
            if errorResult is not None:
                raise ExchangeError(self.id + ' checkERC20Allowance() failed to fetch allowance: ' + self.json(response))
        return result

    def approve_erc20(self, tokenAddress: Str, spenderAddress: Str, amount: Str = None):
        rpcUrl = self.get_rpc_url_option()
        if rpcUrl is None:
            raise ExchangeError(self.id + ' approveERC20() requires rpcUrls[' + self.options['network'] + '] to be configured')
        privateKey = self.normalize_private_key(self.privateKey)
        ownerAddress = self.derive_wallet_address_from_private_key()
        approvalAmount = amount if (amount is not None) else '0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'
        spenderPadded = self.remove0x_prefix(spenderAddress).rjust(64, '0')
        amountHex = approvalAmount
        if amountHex.startswith('0x'):
            amountHex = '0x' + self.remove0x_prefix(amountHex).rjust(64, '0')
        else:
            numericValue = int(amountHex)
            amountHex = '0x' + numericValue.toString(16).rjust(64, '0')
        data = '0x095ea7b3' + spenderPadded + self.remove0x_prefix(amountHex)
        nonceRequest = {
            'jsonrpc': '2.0',
            'method': 'eth_getTransactionCount',
            'params': [self.hex_with0x_prefix(ownerAddress), 'latest'],
            'id': 2,
        }
        nonceResponse = self.fetch(rpcUrl, 'POST', {'Content-Type': 'application/json'}, self.json(nonceRequest))
        nonce = self.safe_string(nonceResponse, 'result')
        gasPriceRequest = {
            'jsonrpc': '2.0',
            'method': 'eth_gasPrice',
            'params': [],
            'id': 3,
        }
        gasPriceResponse = self.fetch(rpcUrl, 'POST', {'Content-Type': 'application/json'}, self.json(gasPriceRequest))
        gasPrice = self.safe_string(gasPriceResponse, 'result')
        chainId = self.get_chain_id_option()
        tx = {
            'nonce': nonce,
            'gasPrice': gasPrice,
            'gasLimit': '0x186a0',  # 100000 in hex
            'to': tokenAddress,
            'value': '0x0',
            'data': data,
            'chainId': chainId,
        }
        txFields = [
            tx['nonce'],
            tx['gasPrice'],
            tx['gasLimit'],
            tx['to'],
            tx['value'],
            tx['data'],
            '0x' + chainId.toString(16),
            '0x',
            '0x',
        ]
        rlpEncoded = self.encode_rlp(txFields)
        txHash = '0x' + self.binary_to_base16(keccak(self.base16_to_binary(self.remove0x_prefix(rlpEncoded))))
        privateKeyBytes = self.base16_to_binary(self.remove0x_prefix(privateKey))
        hashBytes = self.base16_to_binary(self.remove0x_prefix(txHash))
        signature = secp256k1.sign(hashBytes, privateKeyBytes)
        compact = signature.toCompactHex()
        r = compact[0:64]
        s = compact[64:]
        recovery = signature.recovery
        v = (chainId * 2) + 35 + recovery
        signedTxFields = [
            tx['nonce'],
            tx['gasPrice'],
            tx['gasLimit'],
            tx['to'],
            tx['value'],
            tx['data'],
            '0x' + v.toString(16),
            '0x' + r,
            '0x' + s,
        ]
        signedRlp = self.encode_rlp(signedTxFields)
        broadcastRequest = {
            'jsonrpc': '2.0',
            'method': 'eth_sendRawTransaction',
            'params': [signedRlp],
            'id': 4,
        }
        broadcastResponse = self.fetch(rpcUrl, 'POST', {'Content-Type': 'application/json'}, self.json(broadcastRequest))
        txHashResult = self.safe_string(broadcastResponse, 'result')
        error = self.safe_value(broadcastResponse, 'error')
        if error is not None:
            raise ExchangeError(self.id + ' approveERC20() failed: ' + self.json(error))
        return {
            'txHash': txHashResult,
            'token': tokenAddress,
            'spender': spenderAddress,
            'amount': approvalAmount,
        }

    def encode_rlp_item(self, value: str) -> str:
        hex = value
        if not hex.startswith('0x'):
            hex = '0x' + hex
        hex = self.remove0x_prefix(hex).lower()
        while(len(hex) > 1 and hex[0] == '0'):
            hex = hex[1:]
        if len(hex) == 0:
            hex = '0'
        if len(hex) % 2 != 0:
            hex = '0' + hex
        if hex == '00' or hex == '':
            return '80'
        length = len(hex) / 2
        if length == 1 and int(hex, 16) < 128:
            return hex
        if length < 56:
            return(128 + length).toString(16).rjust(2, '0') + hex
        lengthHex = length.toString(16)
        lengthOfLength = int(math.ceil(len(lengthHex) / 2))
        paddedLengthHex = lengthHex.rjust(lengthOfLength * 2, '0')
        return(183 + lengthOfLength).toString(16) + paddedLengthHex + hex

    def encode_rlp(self, fields: List[Any]) -> str:
        encoded = []
        for i in range(0, len(fields)):
            encoded.append(self.encode_rlp_item(fields[i]))
        concatenated = ''.join(encoded)
        totalLength = len(concatenated) / 2
        if totalLength < 56:
            return '0x' + (192 + totalLength).toString(16).rjust(2, '0') + concatenated
        lengthHex = totalLength.toString(16)
        lengthOfLength = int(math.ceil(len(lengthHex) / 2))
        paddedLengthHex = lengthHex.rjust(lengthOfLength * 2, '0')
        return '0x' + (247 + lengthOfLength).toString(16) + paddedLengthHex + concatenated

    def compute_typed_data_digest(self, domain: dict, types: dict, message: dict):
        encoder: Any = TypedDataEncoder
        if callable(encoder.hash):
            return encoder.hash(domain, types, message)
        encoded = encoder.encode(domain, types, message)
        encodedBinary = self.base16_to_binary(encoded[2:])
        digestBytes = keccak(encodedBinary)
        return '0x' + self.binary_to_base16(digestBytes)

    def hash_ethereum_signed_message(self, messageHex: Str):
        if messageHex is None:
            return None
        binaryMessage = self.base16_to_binary(self.remove0x_prefix(messageHex))
        if len(binaryMessage) != 32:
            raise ExchangeError(self.id + ' hashEthereumSignedMessage() requires a 32-byte digest hex string')
        messageLength = self.binary_length(binaryMessage)
        # eslint-disable-next-line quotes
        prefixString = "\x19Ethereum Signed Message:\n" + self.number_to_string(messageLength)
        prefixBinary = self.encode(prefixString)
        prefixed = self.binary_concat(prefixBinary, binaryMessage)
        digestBytes = keccak(prefixed)
        return '0x' + self.binary_to_base16(digestBytes)

    def sign_digest(self, digest: Str, privateKey: Str, usePersonalSign: bool = False):
        normalizedKey = self.normalize_private_key(privateKey)
        if digest is None or normalizedKey is None:
            return None
        hashToSign = digest
        if usePersonalSign:
            hashToSign = self.hash_ethereum_signed_message(digest)
        digestBytes = self.base16_to_binary(self.remove0x_prefix(hashToSign))
        privateKeyBytes = self.base16_to_binary(self.remove0x_prefix(normalizedKey))
        signature = secp256k1.sign(digestBytes, privateKeyBytes)
        compact = signature.toCompactHex()
        recovery = signature.recovery
        r = compact[0:64]
        s = compact[64:]
        vValue = recovery + 27
        vHex = vValue.toString(16).rjust(2, '0')
        return '0x' + r + s + vHex

    def sign_order_payload(self, order: dict, signingScheme: Str = 'eip712'):
        privateKey = self.normalize_private_key(self.privateKey)
        chainId = self.get_chain_id_option()
        verifyingContract = self.get_verifying_contract_option()
        domain = {
            'name': 'Gnosis Protocol',
            'version': 'v2',
            'chainId': chainId,
            'verifyingContract': verifyingContract,
        }
        receiverAddress = self.safe_string(order, 'receiver')
        normalizedReceiver = '0x0000000000000000000000000000000000000000'
        if receiverAddress is not None:
            normalizedReceiver = getAddress(self.hex_with0x_prefix(receiverAddress))
        message = {
            'sellToken': getAddress(self.hex_with0x_prefix(order['sellToken'])),
            'buyToken': getAddress(self.hex_with0x_prefix(order['buyToken'])),
            'receiver': normalizedReceiver,
            'sellAmount': self.safe_string(order, 'sellAmount'),
            'buyAmount': self.safe_string(order, 'buyAmount'),
            'validTo': self.safe_integer(order, 'validTo'),
            'appData': self.hex_with0x_prefix(self.safe_string(order, 'appData')),
            'feeAmount': self.safe_string(order, 'feeAmount', '0'),
            'kind': self.safe_string_lower(order, 'kind'),
            'partiallyFillable': self.safe_bool(order, 'partiallyFillable', False),
            'sellTokenBalance': self.safe_string_lower(order, 'sellTokenBalance', 'erc20'),
            'buyTokenBalance': self.safe_string_lower(order, 'buyTokenBalance', 'erc20'),
        }
        types = {
            'Order': [
                {'name': 'sellToken', 'type': 'address'},
                {'name': 'buyToken', 'type': 'address'},
                {'name': 'receiver', 'type': 'address'},
                {'name': 'sellAmount', 'type': 'uint256'},
                {'name': 'buyAmount', 'type': 'uint256'},
                {'name': 'validTo', 'type': 'uint32'},
                {'name': 'appData', 'type': 'bytes32'},
                {'name': 'feeAmount', 'type': 'uint256'},
                {'name': 'kind', 'type': 'string'},
                {'name': 'partiallyFillable', 'type': 'bool'},
                {'name': 'sellTokenBalance', 'type': 'string'},
                {'name': 'buyTokenBalance', 'type': 'string'},
            ],
        }
        typedDataEncoder = TypedDataEncoder(types)
        domainSeparator = TypedDataEncoder.hashDomain(domain)
        structHash = typedDataEncoder.hash(message)
        prefix = '0x1901'
        encoded = prefix + domainSeparator[2:] + structHash[2:]
        digest = '0x' + self.binary_to_base16(keccak(self.base16_to_binary(encoded[2:])))
        usePersonalSign = (signingScheme == 'ethsign')
        return self.sign_digest(digest, privateKey, usePersonalSign)

    def sign_order_cancellation(self, orderUids: List[Str], signingScheme: Str = 'eip712'):
        privateKey = self.normalize_private_key(self.privateKey)
        chainId = self.get_chain_id_option()
        verifyingContract = self.get_verifying_contract_option()
        domain = {
            'name': 'Gnosis Protocol',
            'version': 'v2',
            'chainId': chainId,
            'verifyingContract': verifyingContract,
        }
        typeString = 'OrderCancellations(bytes[] orderUids)'
        typeHash = '0x' + self.binary_to_base16(keccak(typeString))
        concatenatedHashes = ''
        for i in range(0, len(orderUids)):
            uid = self.hex_with0x_prefix(orderUids[i])
            uidBytes = self.base16_to_binary(uid[2:])
            uidHash = keccak(uidBytes)
            concatenatedHashes += self.binary_to_base16(uidHash)
        arrayHash = '0x' + self.binary_to_base16(keccak(self.base16_to_binary(concatenatedHashes)))
        structHashInput = typeHash[2:] + arrayHash[2:]
        structHash = '0x' + self.binary_to_base16(keccak(self.base16_to_binary(structHashInput)))
        domainSeparator = TypedDataEncoder.hashDomain(domain)
        prefix = '0x1901'
        encoded = prefix + domainSeparator[2:] + structHash[2:]
        digest = '0x' + self.binary_to_base16(keccak(self.base16_to_binary(encoded[2:])))
        if signingScheme == 'ethsign':
            prefixedDigest = self.hash_ethereum_signed_message(digest)
            return self.sign_digest(prefixedDigest, privateKey, False)
        else:
            return self.sign_digest(digest, privateKey, False)

    def compare_quote_with_other_exchanges(self, symbol: Str, amount: float, otherExchanges: List[Any] = [], params={}):
        """
        get a quote from CoW Protocol and compare it with quotes from other exchanges

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str symbol: unified market symbol
        :param float amount: the amount of base currency to trade
        :param dict[] otherExchanges: array of exchange instances to compare quotes with
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param str [params.receiver]: the address to receive the bought tokens
        :param str [params.from]: the address placing the order
        :param int [params.validFor]: quote validity duration in seconds
        :returns dict: a comparison object with CoW quote and other exchange quotes
        """
        self.load_markets()
        market = self.market(symbol)
        marketInfo = self.safe_value(market, 'info', {})
        baseInfo = self.safe_value(marketInfo, 'base', {})
        quoteInfo = self.safe_value(marketInfo, 'quote', {})
        baseDecimals = self.safe_string(baseInfo, 'decimals')
        quoteDecimals = self.safe_string(quoteInfo, 'decimals')
        owner: Str = None
        owner, params = self.ensure_owner_address(params)
        receiverParam = self.safe_string_lower(params, 'receiver', owner)
        fromParam = self.safe_string_lower(params, 'from', owner)
        amountString = self.number_to_string(amount)
        sellAmountRaw = self.amount_to_token_amount(amountString, baseDecimals)
        nowSeconds = self.seconds()
        validFor = self.safe_integer(params, 'validFor', self.safe_integer(self.options, 'defaultValidFor', 30))
        validTo = self.safe_integer(params, 'validTo', nowSeconds + validFor)
        params = self.omit(params, ['validFor', 'validTo', 'receiver', 'from'])
        quoteRequest = self.extend({
            'sellToken': self.address_with0x_prefix(market['baseId']),
            'buyToken': self.address_with0x_prefix(market['quoteId']),
            'sellAmountBeforeFee': sellAmountRaw,
            'receiver': self.address_with0x_prefix(receiverParam),
            'from': self.address_with0x_prefix(fromParam),
            'kind': 'sell',
            'partiallyFillable': False,
            'validTo': validTo,
            'sellTokenBalance': 'erc20',
            'buyTokenBalance': 'erc20',
        }, params)
        quoteResponse = self.publicPostApiV1Quote(quoteRequest)
        quote = self.safe_dict(quoteResponse, 'quote', quoteResponse)
        cowSellAmountRaw = self.safe_string(quote, 'sellAmount', sellAmountRaw)
        cowBuyAmountRaw = self.safe_string(quote, 'buyAmount')
        cowFeeRaw = self.safe_string(quote, 'feeAmount', '0')
        cowBuyAmount = self.convert_token_amount(cowBuyAmountRaw, quoteDecimals)
        effectiveAmount = self.convert_token_amount(cowSellAmountRaw, baseDecimals)
        cowFee = self.convert_token_amount(cowFeeRaw, baseDecimals)
        cowPrice = None
        if (cowBuyAmount is not None) and (effectiveAmount is not None) and (not Precise.string_eq(effectiveAmount, '0')):
            cowPrice = self.parse_number(Precise.string_div(cowBuyAmount, effectiveAmount))
        comparisons = []
        for i in range(0, len(otherExchanges)):
            exchange = otherExchanges[i]
            comparison = {
                'exchange': None,
                'available': None,
                'cost': None,
                'price': None,
                'slippage': None,
                'error': None,
                'info': None,
            }
            try:
                if exchange is None:
                    continue
                comparison['exchange'] = exchange.id
                if (exchange.has is not None) and (exchange.has['fetchOrderBook'] is not None) and not exchange.has['fetchOrderBook']:
                    comparison['error'] = 'fetchOrderBook not supported'
                    comparisons.append(comparison)
                    continue
                exchange.loadMarkets()
                orderBook = exchange.fetchOrderBook(symbol)
                comparison['info'] = orderBook
                asks = self.safe_list(orderBook, 'asks', orderBook['asks'])
                remaining = amountString
                cost = '0'
                filled = '0'
                for j in range(0, len(asks)):
                    level = asks[j]
                    price = self.number_to_string(level[0])
                    size = self.number_to_string(level[1])
                    if (price is None) or (size is None):
                        continue
                    if Precise.string_le(remaining, '0'):
                        break
                    tradeAmount = Precise.string_min(remaining, size)
                    cost = Precise.string_add(cost, Precise.string_mul(tradeAmount, price))
                    filled = Precise.string_add(filled, tradeAmount)
                    remaining = Precise.string_sub(remaining, tradeAmount)
                if Precise.string_le(filled, '0'):
                    comparison['error'] = 'insufficient liquidity'
                    comparisons.append(comparison)
                    continue
                filledNumber = self.parse_number(filled)
                costNumber = self.parse_number(cost)
                priceNumber = None
                if filledNumber is not None and filledNumber > 0 and costNumber is not None:
                    priceNumber = costNumber / filledNumber
                slippage = None
                if (cowPrice is not None) and (priceNumber is not None) and (cowPrice != 0):
                    slippage = (priceNumber - cowPrice) / cowPrice
                comparison = self.extend(comparison, {
                    'available': filledNumber,
                    'cost': costNumber,
                    'price': priceNumber,
                    'slippage': slippage,
                    'remaining': self.parse_number(remaining),
                })
            except Exception as error:
                errorMessage = self.json(error)
                if isinstance(error, Error):
                    errorMessage = error.message
                comparison['error'] = errorMessage
            comparisons.append(comparison)
        return {
            'symbol': symbol,
            'amount': amount,
            'price': self.parse_number(cowPrice),
            'buyAmount': self.parse_number(cowBuyAmount),
            'sellAmount': self.parse_number(effectiveAmount),
            'fee': self.parse_number(cowFee),
            'info': quoteResponse,
            'comparisons': comparisons,
        }

    def wait_for_order(self, id: Str, symbol: Str = None, status: Str = None, params={}) -> Order:
        """
        polls the exchange until an order reaches a terminal status

        https://docs.cow.fi/cow-protocol/reference/apis/orderbook

        :param str id: order id(UID)
        :param str symbol: unified market symbol
        :param str [status]: specific status to wait for(defaults to any terminal status)
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :param int [params.pollingDelay]: delay between polling requests in milliseconds(default 2000)
        :param int [params.timeout]: maximum time to wait in milliseconds(default 60000)
        :returns dict: an [order structure](https://docs.ccxt.com/#/?id=order-structure)
        """
        self.load_markets()
        options = self.safe_value(self.options, 'waitForOrder', {})
        statuses = self.safe_value(options, 'statuses', ['closed', 'canceled', 'expired', 'rejected'])
        targetStatuses = statuses if (status is None) else [status]
        defaultPollingDelay = self.safe_integer(options, 'pollingDelay', 2000)
        defaultTimeout = self.safe_integer(options, 'timeout', 60000)
        pollingDelay = self.safe_integer(params, 'pollingDelay', defaultPollingDelay)
        timeout = self.safe_integer(params, 'timeout', defaultTimeout)
        fetchParams = self.omit(params, ['pollingDelay', 'timeout'])
        deadline = self.milliseconds() + timeout
        # eslint-disable-next-line no-constant-condition
        while(True):
            order = self.fetch_order(id, symbol, fetchParams)
            orderStatus = self.safe_string(order, 'status')
            if self.in_array(orderStatus, targetStatuses):
                return order
            if self.milliseconds() > deadline:
                raise InvalidOrder(self.id + ' waitForOrder() timed out waiting for order ' + id + ' to reach status ' + ','.join(targetStatuses))
            self.sleep(pollingDelay)

    def handle_errors(self, httpCode: Int, reason: str, url: str, method: str, headers: dict, body: str, response, requestHeaders, requestBody):
        if response is None:
            return
        errorType = self.safe_string(response, 'errorType')
        if errorType is not None:
            description = self.safe_string(response, 'description')
            feedback = self.id + ' ' + (description is body if None else description)
            errors = {
                'DuplicatedOrder': InvalidOrder,
                'OrderAlreadyExists': InvalidOrder,
                'InvalidOrder': InvalidOrder,
                'InsufficientFee': InvalidOrder,
                'InsufficientFunds': InsufficientFunds,
                'UnknownOrder': OrderNotFound,
                'OrderNotFound': OrderNotFound,
                'OrderExpired': OrderNotFound,
                'InvalidSignature': AuthenticationError,
                'UnsupportedSellToken': BadSymbol,
                'UnsupportedBuyToken': BadSymbol,
                'UnsupportedSigningScheme': AuthenticationError,
                'InvalidAppData': BadRequest,
                'SellAmountDoesNotCoverFee': InvalidOrder,
                'SlippageTooLarge': InvalidOrder,
                'NoLiquidity': InvalidOrder,
            }
            Exception = self.safe_value(errors, errorType, ExchangeError)
            raise Exception(feedback)
        errorsList = self.safe_list(response, 'errors')
        if errorsList is not None:
            for i in range(0, len(errorsList)):
                error = errorsList[i]
                type = self.safe_string(error, 'errorType')
                if type is not None:
                    description = self.safe_string(error, 'description')
                    feedback = self.id + ' ' + (description is self.json(error) if None else description)
                    errors = {
                        'DuplicatedOrder': InvalidOrder,
                        'InvalidOrder': InvalidOrder,
                        'InsufficientFee': InvalidOrder,
                        'InsufficientFunds': InsufficientFunds,
                        'UnsupportedSellToken': BadSymbol,
                        'UnsupportedBuyToken': BadSymbol,
                        'NoLiquidity': InvalidOrder,
                    }
                    Exception = self.safe_value(errors, type, ExchangeError)
                    raise Exception(feedback)
        status = self.safe_string(response, 'status')
        if status is not None:
            knownOrderStatuses = ['open', 'pending', 'pending-solver-submission', 'presignatureAwaiting', 'presignaturePending', 'fulfilled', 'expired', 'solved', 'cancelled', 'canceled', 'retracted', 'failed']
            if not self.in_array(status, knownOrderStatuses):
                if (status != 'success') and (status != 'ok'):
                    description = self.safe_string(response, 'description')
                    feedback = self.id + ' ' + (description is body if None else description)
                    raise ExchangeError(feedback)
