// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class cow : Exchange
{
    public cow (object args = null): base(args) {}

    public async Task<object> publicGetApiV1OrdersUid (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV1OrdersUid",parameters);
    }

    public async Task<object> publicGetApiV1Trades (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV1Trades",parameters);
    }

    public async Task<object> publicGetApiV1AccountOwnerOrders (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV1AccountOwnerOrders",parameters);
    }

    public async Task<object> publicPostApiV1Quote (object parameters = null)
    {
        return await this.callAsync ("publicPostApiV1Quote",parameters);
    }

    public async Task<object> publicPostApiV1Orders (object parameters = null)
    {
        return await this.callAsync ("publicPostApiV1Orders",parameters);
    }

    public async Task<object> publicDeleteApiV1Orders (object parameters = null)
    {
        return await this.callAsync ("publicDeleteApiV1Orders",parameters);
    }

}