// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *CowCore) PublicGetApiV1OrdersUid (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV1OrdersUid", args...)
}

func (this *CowCore) PublicGetApiV1Trades (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV1Trades", args...)
}

func (this *CowCore) PublicGetApiV1AccountOwnerOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV1AccountOwnerOrders", args...)
}

func (this *CowCore) PublicPostApiV1Quote (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicPostApiV1Quote", args...)
}

func (this *CowCore) PublicPostApiV1Orders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicPostApiV1Orders", args...)
}

func (this *CowCore) PublicDeleteApiV1Orders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicDeleteApiV1Orders", args...)
}
