# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.abstract.cow import ImplicitAPI
from ccxt.base.types import Any
from ccxt.base.decimal_to_precision import TICK_SIZE


class cow(Exchange, ImplicitAPI):

    def describe(self) -> Any:
        return self.deep_extend(super(cow, self).describe(), {
            'id': 'cow',
            'name': 'CoW Protocol(Order Book API)',
            'countries': [],
            'rateLimit': 100,
            'has': {
                'spot': True,
                'createOrder': True,      # POST /orders(signed body)
                'cancelOrder': True,      # DELETE /orders(signed body)
                'fetchOrder': True,       # GET /orders/{uid}
                'fetchMyTrades': True,    # GET /trades?owner=... | orderUid=...
                # explicitly not supported by CoW:
                'fetchTicker': False,
                'fetchTickers': False,
                'fetchOrderBook': False,
                'fetchTrades': False,
                'fetchBalance': False,
            },
            'urls': {
                # CCXT will pass self into your sign() – compute the real base there
                'api': 'https://api.cow.fi',
                'www': 'https://cow.fi',
                'doc': 'https://docs.cow.fi/cow-protocol/reference/apis/orderbook',
            },
            # CCXT’s implicit API generator wants self “api” map:
            'api': {
                'public': {
                    'get': [
                        'api/v1/orders/{uid}',
                        'api/v1/trades',
                        'api/v1/account/{owner}/orders',
                    ],
                    'post': ['api/v1/quote', 'api/v1/orders'],
                    'delete': ['api/v1/orders'],
                },
            },
            'options': {
                # You can override these from user code: new ccxt.cow({options: {network: 'base', env: 'prod'}})
                'network': 'mainnet',  # 'mainnet' | 'xdai' | 'arbitrum_one' | 'base' | 'sepolia'
                'env': 'prod',        # 'prod' | 'barn'
            },
            'precisionMode': TICK_SIZE,
        })
