<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\cow as Exchange;

class cow extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'cow',
            'name' => 'CoW Protocol (Order Book API)',
            'countries' => array(),
            'rateLimit' => 100,
            'has' => array(
                'spot' => true,
                'createOrder' => true,      // POST /orders (signed body)
                'cancelOrder' => true,      // DELETE /orders (signed body)
                'fetchOrder' => true,       // GET /orders/{uid}
                'fetchMyTrades' => true,    // GET /trades?owner=... | orderUid=...
                // explicitly not supported by CoW:
                'fetchTicker' => false,
                'fetchTickers' => false,
                'fetchOrderBook' => false,
                'fetchTrades' => false,
                'fetchBalance' => false,
            ),
            'urls' => array(
                // CCXT will pass this into your sign() – compute the real base there
                'api' => 'https://api.cow.fi',
                'www' => 'https://cow.fi',
                'doc' => 'https://docs.cow.fi/cow-protocol/reference/apis/orderbook',
            ),
            // CCXT’s implicit API generator wants this “api” map:
            'api' => array(
                'public' => array(
                    'get' => array(
                        'api/v1/orders/{uid}',
                        'api/v1/trades',
                        'api/v1/account/{owner}/orders',
                    ),
                    'post' => array( 'api/v1/quote', 'api/v1/orders' ),
                    'delete' => array( 'api/v1/orders' ),
                ),
            ),
            'options' => array(
                // You can override these from user code => new \ccxt\cow(array( options => array( network => 'base', env => 'prod' )))
                'network' => 'mainnet', // 'mainnet' | 'xdai' | 'arbitrum_one' | 'base' | 'sepolia'
                'env' => 'prod',        // 'prod' | 'barn'
            ),
            'precisionMode' => TICK_SIZE,
        ));
    }
}
