<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\cow as Exchange;

class cow extends Exchange {

    public function describe(): mixed {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'cow',
            'name' => 'CoW Protocol',
            'countries' => array(),
            'rateLimit' => 500,
            'has' => array(
                'spot' => true,
                'fetchMarkets' => true,
                'fetchBalance' => true,
                'createOrder' => true,      // POST /orders (signed body)
                'cancelOrder' => true,      // DELETE /orders (signed body)
                'cancelAllOrders' => true,  // cancel multiple open orders
                'fetchOrder' => true,       // GET /orders/{uid}
                'fetchOrders' => true,      // GET /account/{owner}/orders
                'fetchOpenOrders' => true,
                'fetchClosedOrders' => true,
                'fetchCanceledOrders' => true,
                'fetchMyTrades' => true,
                'fetchTicker' => false,
                'fetchTickers' => false,
                'fetchOrderBook' => false,
                'fetchTrades' => false,
                'fetchCurrencies' => false,
            ),
            'features' => array(
                'spot' => array(
                    'sandbox' => true, // barn environment serves
                    'createOrder' => array(
                        'marginMode' => false,
                        'triggerPrice' => false,
                        'triggerDirection' => false,
                        'triggerPriceType' => null,
                        'stopLossPrice' => false,
                        'takeProfitPrice' => false,
                        'attachedStopLossTakeProfit' => null,
                        'timeInForce' => array(
                            'GTC' => true,  // Good Till Cancelled (default)
                            'IOC' => true,  // Immediate Or Cancel
                            'FOK' => true,  // Fill Or Kill
                            'PO' => false,  // Post Only
                            'GTD' => false, // Good Till Date
                        ),
                        'hedged' => false,
                        'trailing' => false,
                        'leverage' => false,
                        'marketBuyByCost' => false,
                        'marketBuyRequiresPrice' => false,
                        'selfTradePrevention' => false,
                        'iceberg' => false,
                    ),
                    'createOrders' => null,
                    'fetchMyTrades' => array(
                        'marginMode' => false,
                        'limit' => 1000, // API default limit
                        'daysBack' => null,
                        'untilDays' => null,
                        'symbolRequired' => false,
                    ),
                    'fetchOrder' => array(
                        'marginMode' => false,
                        'trigger' => false,
                        'trailing' => false,
                        'symbolRequired' => false,
                    ),
                    'fetchOpenOrders' => array(
                        'marginMode' => false,
                        'limit' => 1000,
                        'trigger' => false,
                        'trailing' => false,
                        'symbolRequired' => false,
                    ),
                    'fetchOrders' => array(
                        'marginMode' => false,
                        'limit' => 1000,
                        'daysBack' => null,
                        'untilDays' => null,
                        'trigger' => false,
                        'trailing' => false,
                        'symbolRequired' => false,
                    ),
                    'fetchClosedOrders' => array(
                        'marginMode' => false,
                        'limit' => 1000,
                        'daysBack' => null,
                        'daysBackCanceled' => null,
                        'untilDays' => null,
                        'trigger' => false,
                        'trailing' => false,
                        'symbolRequired' => false,
                    ),
                    'fetchOHLCV' => array(
                        'limit' => null,
                    ),
                ),
            ),
            'requiredCredentials' => array(
                'apiKey' => false,
                'secret' => false,
                'uid' => false,
                'login' => false,
                'password' => false,
                'twofa' => false,
                'token' => false,
                'walletAddress' => true,
                'privateKey' => true,
            ),
            'urls' => array(
                'api' => 'https://api.cow.fi',
                'www' => 'https://cow.fi',
                'doc' => 'https://docs.cow.fi/cow-protocol/reference/apis/orderbook',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'api/v1/orders/{uid}' => 1,
                        'api/v1/trades' => 1,
                        'api/v1/account/{owner}/orders' => 1,
                    ),
                    'post' => array(
                        'api/v1/quote' => 12,
                        'api/v1/orders' => 1,
                    ),
                    'delete' => array(
                        'api/v1/orders' => 1,
                    ),
                ),
            ),
            'options' => array(
                'network' => 'mainnet',
                'env' => 'prod',
                'hosts' => array(
                    'prod' => 'https://api.cow.fi',
                    'barn' => 'https://barn.api.cow.fi',
                ),
                'networkIds' => array(
                    'mainnet' => 'mainnet',
                    'xdai' => 'xdai',
                    'arbitrum_one' => 'arbitrum-one',
                    'base' => 'base',
                    'sepolia' => 'sepolia',
                ),
                'defaultQuoteTokens' => array( 'USDC', 'USDT', 'DAI', 'WETH' ),
                'walletAddress' => null,
                'tokenListUrl' => 'https://files.cow.fi/tokens/CowSwap.json',
                'chainIds' => array(
                    'mainnet' => 1,
                    'xdai' => 100,
                    'arbitrum_one' => 42161,
                    'base' => 8453,
                    'sepolia' => 11155111,
                ),
                'verifyingContracts' => array(
                    'mainnet' => '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                    'xdai' => '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                    'arbitrum_one' => '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                    'base' => '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                    'sepolia' => '0x9008D19f58AAbD9eD0D60971565AA8510560ab41',
                ),
                'vaultRelayers' => array(
                    'mainnet' => '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                    'xdai' => '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                    'arbitrum_one' => '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                    'base' => '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                    'sepolia' => '0xC92E8bdf79f0507f65a392b0ab4667716BFE0110',
                ),
                'rpcUrls' => array(
                    'mainnet' => 'https://eth.llamarpc.com',
                    'xdai' => 'https://rpc.gnosischain.com',
                    'arbitrum_one' => 'https://arb1.arbitrum.io/rpc',
                    'base' => 'https://mainnet.base.org',
                    'sepolia' => 'https://rpc.sepolia.org',
                ),
                'autoApprove' => true, // Automatically approve VaultRelayer if allowance is insufficient
                'cancellationVerifyingContract' => '0x0000000000000000000000000000000000000000',
                'defaultValidFor' => 30,
                'defaultAppData' => '0x0000000000000000000000000000000000000000000000000000000000000000',
                'defaultSigningScheme' => 'ethsign',
                'tokenBalances' => array(
                    'erc20' => 0,
                    'external' => 1,
                    'internal' => 2,
                ),
                'orderKinds' => array(
                    'sell' => 0,
                    'buy' => 1,
                ),
                'waitForOrder' => array(
                    'pollingDelay' => 2000,
                    'timeout' => 60000,
                    'statuses' => array( 'closed', 'canceled', 'expired', 'rejected' ),
                ),
            ),
            'precisionMode' => TICK_SIZE,
            'fees' => array(
                'trading' => array(
                    'tierBased' => false,
                    'percentage' => true,
                    'maker' => $this->parse_number('0'),
                    'taker' => $this->parse_number('0'),
                ),
            ),
        ));
    }

    public function resolve_orderbook_base_url(?string $network = null, ?string $env = null): string {
        $defaultNetwork = $this->safe_string($this->options, 'network', 'mainnet');
        $selectedNetwork = ($network === null) ? $defaultNetwork : $network;
        $defaultEnv = $this->safe_string($this->options, 'env', 'prod');
        $selectedEnv = ($env === null) ? $defaultEnv : $env;
        $networkMap = $this->safe_value($this->options, 'networkIds', array());
        $networkId = $this->safe_string($networkMap, $selectedNetwork);
        if ($networkId === null) {
            throw new ExchangeError($this->id . ' resolveOrderbookBaseUrl() unsupported $network => ' . $selectedNetwork);
        }
        $hosts = $this->safe_value($this->options, 'hosts', array());
        $host = $this->safe_string($hosts, $selectedEnv);
        if ($host === null) {
            throw new ExchangeError($this->id . ' resolveOrderbookBaseUrl() unsupported environment => ' . $selectedEnv);
        }
        return $host . '/' . $networkId . '/api/v1';
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $paramsWithoutPath = $this->omit($params, $this->extract_params($path));
        $network = $this->safe_string_2($paramsWithoutPath, 'network', 'chainId');
        $env = $this->safe_string($paramsWithoutPath, 'env');
        $query = $this->omit($paramsWithoutPath, array( 'network', 'chainId', 'env' ));
        $baseUrl = $this->resolve_orderbook_base_url($network, $env);
        $pathWithParams = $this->implode_params($path, $params);
        $versionPrefix = 'api/v1/';
        if (mb_strpos($pathWithParams, $versionPrefix) === 0) {
            $pathWithParams = str_replace($versionPrefix, '', $pathWithParams);
        }
        $url = $baseUrl;
        if (strlen($pathWithParams) > 0) {
            $url = $url . '/' . $pathWithParams;
        }
        if (($method === 'GET') || ($method === 'DELETE')) {
            if (!$this->is_empty($query)) {
                $url = $url . '?' . $this->urlencode($query);
            }
        } else {
            if (!$this->is_empty($query)) {
                $body = $this->json($query);
            }
            $headers = $this->extend(array(), $headers);
            $headers['Content-Type'] = 'application/json';
        }
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }

    public function fetch_markets($params = array ()): array {
        /**
         * retrieves data on all $markets for CoW Protocol
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {array} [$params] extra $parameters specific to the exchange API endpoint
         * @param {string} [$params->tokenListUrl] override the default $token list URL
         * @param {Array} [$params->tokens] manually provide a $token list instead of fetching
         * @param {Array} [$params->quoteSymbols] override default $quote symbols (USDC, USDT, DAI, WETH)
         * @param {int} [$params->chainId] override the chain ID for filtering $tokens
         * @return {array[]} an array of objects representing market data
         */
        $parameters = $this->extend(array(), $params);
        $tokenListUrl = $this->safe_string($parameters, 'tokenListUrl', $this->safe_string($this->options, 'tokenListUrl', 'https://files.cow.fi/tokens/CowSwap.json'));
        $overrideTokens = $this->safe_list($parameters, 'tokens');
        $overrideQuotes = $this->safe_value($parameters, 'quoteSymbols');
        $overrideChainId = $this->safe_integer($parameters, 'chainId');
        $tokenList = null;
        if ($overrideTokens !== null) {
            $tokenList = array( 'tokens' => $overrideTokens );
        } else {
            $tokenList = $this->fetch($tokenListUrl, 'GET', null, null);
        }
        $tokens = $this->safe_list($tokenList, 'tokens', array());
        $targetChainId = ($overrideChainId === null) ? $this->get_chain_id_option() : $overrideChainId;
        $tokensBySymbol = array();
        for ($i = 0; $i < count($tokens); $i++) {
            $token = $tokens[$i];
            $chainId = $this->safe_integer($token, 'chainId');
            if (($chainId !== null) && ($chainId !== $targetChainId)) {
                continue;
            }
            $symbol = $this->safe_string_upper($token, 'symbol');
            if ($symbol === null) {
                continue;
            }
            $address = $this->safe_string_lower($token, 'address');
            if (!(is_array($tokensBySymbol) && array_key_exists($symbol, $tokensBySymbol))) {
                $tokenRecord = $this->extend(array(), $token);
                if ($address !== null) {
                    $tokenRecord['address'] = $address;
                }
                $tokensBySymbol[$symbol] = $tokenRecord;
            }
        }
        $defaultQuoteSymbols = $this->safe_value($this->options, 'defaultQuoteTokens', array( 'USDC', 'USDT', 'DAI', 'WETH' ));
        $quoteSymbolsRaw = ($overrideQuotes === null) ? $defaultQuoteSymbols : $overrideQuotes;
        $quoteSymbols = array();
        for ($i = 0; $i < count($quoteSymbolsRaw); $i++) {
            $quote = $quoteSymbolsRaw[$i];
            if ($quote !== null) {
                $quoteSymbols[] = strtoupper($quote);
            }
        }
        $marketSymbols = is_array($tokensBySymbol) ? array_keys($tokensBySymbol) : array();
        $markets = array();
        for ($i = 0; $i < count($marketSymbols); $i++) {
            $baseSymbol = $marketSymbols[$i];
            $baseToken = $tokensBySymbol[$baseSymbol];
            $baseAddress = $this->safe_string_lower($baseToken, 'address');
            if ($baseAddress === null) {
                $baseAddress = strtolower($baseSymbol);
            }
            $baseDecimals = $this->safe_integer($baseToken, 'decimals');
            $amountPrecision = ($baseDecimals === null) ? null : $this->parse_number($this->parse_precision($this->number_to_string($baseDecimals)));
            for ($j = 0; $j < count($quoteSymbols); $j++) {
                $quoteSymbolRaw = $quoteSymbols[$j];
                if ($quoteSymbolRaw === null) {
                    continue;
                }
                $quoteSymbol = strtoupper($quoteSymbolRaw);
                if ($baseSymbol === $quoteSymbol) {
                    continue;
                }
                $quoteToken = $this->safe_value($tokensBySymbol, $quoteSymbol);
                if ($quoteToken === null) {
                    continue;
                }
                $quoteAddress = $this->safe_string_lower($quoteToken, 'address');
                if ($quoteAddress === null) {
                    $quoteAddress = strtolower($quoteSymbol);
                }
                $baseCode = $this->safe_currency_code($baseSymbol);
                $quoteCode = $this->safe_currency_code($quoteSymbol);
                $symbol = $baseCode . '/' . $quoteCode;
                $marketId = $baseAddress . '-' . $quoteAddress;
                $markets[] = $this->safe_market_structure(array(
                    'id' => $marketId,
                    'uppercaseId' => null,
                    'symbol' => $symbol,
                    'base' => $baseCode,
                    'quote' => $quoteCode,
                    'baseId' => $baseAddress,
                    'quoteId' => $quoteAddress,
                    'type' => 'spot',
                    'spot' => true,
                    'margin' => false,
                    'swap' => false,
                    'future' => false,
                    'option' => false,
                    'taker' => $this->parse_number('0'),
                    'maker' => $this->parse_number('0'),
                    'contract' => false,
                    'linear' => null,
                    'inverse' => null,
                    'contractSize' => null,
                    'expiry' => null,
                    'expiryDatetime' => null,
                    'strike' => null,
                    'optionType' => null,
                    'settle' => null,
                    'settleId' => null,
                    'active' => true,
                    'limits' => array(
                        'amount' => array(
                            'min' => null,
                            'max' => null,
                        ),
                        'price' => array(
                            'min' => null,
                            'max' => null,
                        ),
                        'cost' => array(
                            'min' => null,
                            'max' => null,
                        ),
                        'leverage' => array(
                            'min' => null,
                            'max' => null,
                        ),
                    ),
                    'precision' => array(
                        'amount' => $amountPrecision,
                        'price' => null,
                    ),
                    'info' => array(
                        'base' => $baseToken,
                        'quote' => $quoteToken,
                    ),
                    'created' => null,
                ));
            }
        }
        return $markets;
    }

    public function parse_trade(array $trade, ?array $market = null): array {
        $sellToken = $this->safe_string_lower($trade, 'sellToken');
        $buyToken = $this->safe_string_lower($trade, 'buyToken');
        $resolvedMarket = $market;
        if (($sellToken !== null) && ($buyToken !== null)) {
            $marketId = $sellToken . '-' . $buyToken;
            $resolvedMarket = $this->safe_market($marketId, $resolvedMarket, null, 'spot');
        }
        $resolvedMarket = $this->safe_market(null, $resolvedMarket, null, 'spot');
        $symbol = $this->safe_string($resolvedMarket, 'symbol');
        $marketInfo = $this->safe_value($resolvedMarket, 'info', array());
        $baseInfo = $this->safe_value($marketInfo, 'base', array());
        $quoteInfo = $this->safe_value($marketInfo, 'quote', array());
        $baseDecimals = $this->safe_string($baseInfo, 'decimals');
        $quoteDecimals = $this->safe_string($quoteInfo, 'decimals');
        $sellAmountRaw = $this->safe_string($trade, 'sellAmount');
        $buyAmountRaw = $this->safe_string($trade, 'buyAmount');
        $feeAmountRaw = $this->safe_string($trade, 'feeAmount');
        $kind = $this->safe_string_lower($trade, 'kind');
        $timestamp = $this->safe_integer($trade, 'timestamp');
        $orderUid = $this->safe_string($trade, 'orderUid');
        $tradeId = $this->safe_string($trade, 'tradeUid');
        $executedSellRaw = $this->safe_string($trade, 'executedSellAmount', $sellAmountRaw);
        $executedBuyRaw = $this->safe_string($trade, 'executedBuyAmount', $buyAmountRaw);
        $baseId = $this->safe_string_lower($resolvedMarket, 'baseId');
        $quoteId = $this->safe_string_lower($resolvedMarket, 'quoteId');
        $side = null;
        $amountRaw = null;
        $costRaw = null;
        if ($baseId === $sellToken) {
            $side = 'sell';
            $amountRaw = $executedSellRaw;
            $costRaw = $executedBuyRaw;
        } elseif ($baseId === $buyToken) {
            $side = 'buy';
            $amountRaw = $executedBuyRaw;
            $costRaw = $executedSellRaw;
        } elseif ($kind !== null) {
            if ($kind === 'buy') {
                $side = 'buy';
            } elseif ($kind === 'sell') {
                $side = 'sell';
            }
            $amountRaw = ($side === 'sell') ? $executedSellRaw : $executedBuyRaw;
            $costRaw = ($side === 'sell') ? $executedBuyRaw : $executedSellRaw;
        } else {
            $amountRaw = $executedSellRaw;
            $costRaw = $executedBuyRaw;
        }
        $amountString = $this->convert_token_amount($amountRaw, $baseDecimals);
        $costString = $this->convert_token_amount($costRaw, $quoteDecimals);
        $price = null;
        if (($amountString !== null) && ($costString !== null) && (!Precise::string_eq($amountString, '0'))) {
            $price = $this->parse_number(Precise::string_div($costString, $amountString));
        }
        $amount = $this->parse_number($amountString);
        $cost = $this->parse_number($costString);
        $fee = null;
        if ($feeAmountRaw !== null) {
            $feeCurrencyId = $this->safe_string_lower($trade, 'feeToken');
            if ($feeCurrencyId === null) {
                $feeCurrencyId = $sellToken;
            }
            $feeCurrencyCode = null;
            if ($feeCurrencyId === $baseId) {
                $feeCurrencyCode = $resolvedMarket['base'];
            } elseif ($feeCurrencyId === $quoteId) {
                $feeCurrencyCode = $resolvedMarket['quote'];
            } else {
                $feeCurrencyCode = $this->safe_currency_code($feeCurrencyId);
            }
            $feeDecimals = ($feeCurrencyId === $baseId) ? $baseDecimals : $quoteDecimals;
            $feeCost = $this->parse_number($this->convert_token_amount($feeAmountRaw, $feeDecimals));
            $fee = array(
                'cost' => $feeCost,
                'currency' => $feeCurrencyCode,
            );
        }
        $takerOrMaker = null;
        return $this->safe_trade(array(
            'info' => $trade,
            'id' => $tradeId,
            'order' => $orderUid,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $symbol,
            'type' => null,
            'side' => $side,
            'price' => $price,
            'amount' => $amount,
            'cost' => $cost,
            'takerOrMaker' => $takerOrMaker,
            'fee' => $fee,
        ), $resolvedMarket);
    }

    public function parse_order_status(?string $status) {
        $statuses = array(
            'open' => 'open',
            'pending' => 'open',
            'pending-solver-submission' => 'open',
            'presignatureAwaiting' => 'open',
            'presignaturePending' => 'open',
            'fulfilled' => 'closed',
            'expired' => 'expired',
            'solved' => 'closed',
            'cancelled' => 'canceled',
            'canceled' => 'canceled',
            'retracted' => 'canceled',
            'failed' => 'rejected',
        );
        return $this->safe_string($statuses, $status, $status);
    }

    public function convert_token_amount(?string $amount, ?string $decimals) {
        if (($amount === null) || ($decimals === null)) {
            return null;
        }
        $decimalsString = $this->number_to_string($decimals);
        $precision = $this->parse_precision($decimalsString);
        return Precise::string_mul($amount, $precision);
    }

    public function parse_order(array $order, ?array $market = null): array {
        $sellToken = $this->safe_string_lower($order, 'sellToken');
        $buyToken = $this->safe_string_lower($order, 'buyToken');
        $kind = $this->safe_string_lower($order, 'kind');
        $side = null;
        if ($kind !== null) {
            if ($kind === 'sell') {
                $side = 'sell';
            } elseif ($kind === 'buy') {
                $side = 'buy';
            }
        }
        $resolvedMarket = $market;
        if ($resolvedMarket === null) {
            if (($sellToken !== null) && ($buyToken !== null)) {
                $directId = $sellToken . '-' . $buyToken;
                $inverseId = $buyToken . '-' . $sellToken;
                $directMarket = $this->safe_value($this->markets_by_id, $directId);
                $inverseMarket = $this->safe_value($this->markets_by_id, $inverseId);
                if (($side === 'sell') && ($directMarket !== null)) {
                    $resolvedMarket = $directMarket;
                } elseif (($side === 'buy') && ($inverseMarket !== null)) {
                    $resolvedMarket = $inverseMarket;
                } elseif ($directMarket !== null) {
                    $resolvedMarket = $directMarket;
                } elseif ($inverseMarket !== null) {
                    $resolvedMarket = $inverseMarket;
                }
            }
        }
        $resolvedMarket = $this->safe_market(null, $resolvedMarket, null, 'spot');
        $symbol = $this->safe_string($resolvedMarket, 'symbol');
        $baseId = $this->safe_string($resolvedMarket, 'baseId');
        $quoteId = $this->safe_string($resolvedMarket, 'quoteId');
        $baseCurrency = $this->safe_string($resolvedMarket, 'base');
        $quoteCurrency = $this->safe_string($resolvedMarket, 'quote');
        if ($side === null) {
            if (($resolvedMarket !== null) && ($sellToken !== null) && ($buyToken !== null)) {
                if (($baseId === $sellToken) && ($quoteId === $buyToken)) {
                    $side = 'sell';
                } elseif (($baseId === $buyToken) && ($quoteId === $sellToken)) {
                    $side = 'buy';
                }
            }
        }
        $marketInfo = $this->safe_value($resolvedMarket, 'info', array());
        $infoBase = $this->safe_value($marketInfo, 'base', array());
        $infoQuote = $this->safe_value($marketInfo, 'quote', array());
        $baseDecimals = $this->safe_string($infoBase, 'decimals');
        $quoteDecimals = $this->safe_string($infoQuote, 'decimals');
        $sellAmountRaw = $this->safe_string($order, 'sellAmount');
        $buyAmountRaw = $this->safe_string($order, 'buyAmount');
        $executedSellRaw = $this->safe_string($order, 'executedSellAmount');
        $executedBuyRaw = $this->safe_string($order, 'executedBuyAmount');
        $amountRaw = null;
        $filledRaw = null;
        $costRaw = null;
        $baseDecimalsUsed = $baseDecimals;
        $quoteDecimalsUsed = $quoteDecimals;
        if ($side === 'sell') {
            $amountRaw = $sellAmountRaw;
            $filledRaw = $executedSellRaw;
            $costRaw = $executedBuyRaw;
        } elseif ($side === 'buy') {
            $amountRaw = $buyAmountRaw;
            $filledRaw = $executedBuyRaw;
            $costRaw = $executedSellRaw;
        } else {
            $amountRaw = $sellAmountRaw;
            $filledRaw = $executedSellRaw;
            $costRaw = $executedBuyRaw;
            if (($baseId === $buyToken) && ($quoteId === $sellToken)) {
                $baseDecimalsUsed = $quoteDecimals;
                $quoteDecimalsUsed = $baseDecimals;
            }
        }
        $amount = null;
        $filled = null;
        $cost = null;
        $remaining = null;
        $costString = null;
        $amountString = $this->convert_token_amount($amountRaw, $baseDecimalsUsed);
        $filledString = $this->convert_token_amount($filledRaw, $baseDecimalsUsed);
        $costString = $this->convert_token_amount($costRaw, $quoteDecimalsUsed);
        if ($amountString !== null) {
            $amount = $this->parse_number($amountString);
        }
        if ($filledString !== null) {
            $filled = $this->parse_number($filledString);
        }
        if ($amountRaw !== null && $filledRaw !== null) {
            $remainingRaw = Precise::string_sub($amountRaw, $filledRaw);
            $remainingString = $this->convert_token_amount($remainingRaw, $baseDecimalsUsed);
            if ($remainingString !== null) {
                $remaining = $this->parse_number($remainingString);
            }
        }
        if ($costString !== null) {
            $cost = $this->parse_number($costString);
        }
        $price = null;
        if (($filledString !== null) && ($costString !== null) && (!Precise::string_eq($filledString, '0'))) {
            $price = $this->parse_number(Precise::string_div($costString, $filledString));
        }
        $feeAmountRaw = $this->safe_string($order, 'feeAmount');
        $fee = null;
        if ($feeAmountRaw !== null) {
            $feeDecimals = $baseDecimalsUsed;
            $feeCurrency = $baseCurrency;
            if ($side === 'buy') {
                $feeDecimals = $quoteDecimalsUsed;
                $feeCurrency = $quoteCurrency;
            }
            $feeAmountString = $this->convert_token_amount($feeAmountRaw, $feeDecimals);
            if ($feeAmountString !== null) {
                $fee = array(
                    'currency' => $feeCurrency,
                    'cost' => $this->parse_number($feeAmountString),
                );
            }
        }
        $statusRaw = $this->safe_string($order, 'status');
        $status = $this->parse_order_status($statusRaw);
        $timestamp = $this->parse8601($this->safe_string_2($order, 'creationDate', 'creationTime'));
        if ($timestamp === null) {
            $timestamp = $this->safe_integer_product($order, 'creationTime', 1000);
        }
        $validTo = $this->safe_integer($order, 'validTo');
        $expiry = ($validTo !== null) ? ($validTo * 1000) : null;
        $orderType = null;
        $postOnly = null;
        $timeInForce = null;
        $clientOrderId = $this->safe_string($order, 'appData');
        $triggerPrice = null;
        $average = $price;
        $lastTradeTimestamp = $this->parse8601($this->safe_string($order, 'executionTime'));
        if ($lastTradeTimestamp === null) {
            $lastTradeTimestamp = $this->safe_integer_product($order, 'executionTime', 1000);
        }
        $result = array(
            'info' => $order,
            'id' => $this->safe_string($order, 'uid'),
            'clientOrderId' => $clientOrderId,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'lastTradeTimestamp' => $lastTradeTimestamp,
            'symbol' => $symbol,
            'type' => $orderType,
            'timeInForce' => $timeInForce,
            'postOnly' => $postOnly,
            'side' => $side,
            'price' => $price,
            'stopPrice' => $triggerPrice,
            'average' => $average,
            'cost' => $cost,
            'amount' => $amount,
            'filled' => $filled,
            'remaining' => $remaining,
            'status' => $status,
            'fee' => $fee,
            'triggerPrice' => $triggerPrice,
            'expiry' => $expiry,
        );
        return $this->safe_order($result, $resolvedMarket);
    }

    public function fetch_order(?string $id, ?string $symbol = null, $params = array ()): array {
        /**
         * fetches information on an $order made by the user
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $id $order $id (UID)
         * @param {string} $symbol unified $symbol of the $market the $order was made in
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @return {array} An [$order structure](https://docs.ccxt.com/#/?$id=$order-structure)
         */
        $this->load_markets();
        $request = array(
            'uid' => $id,
        );
        $response = $this->publicGetApiV1OrdersUid ($this->extend($request, $params));
        $order = $this->safe_dict($response, 'order', $response);
        $market = null;
        if ($symbol !== null) {
            $market = $this->market($symbol);
        }
        return $this->parse_order($order, $market);
    }

    public function fetch_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetches information on multiple orders made by the user
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $symbol unified $market $symbol of the $market orders were made in
         * @param {int} [$since] the earliest time in ms to fetch orders for
         * @param {int} [$limit] the maximum number of order structures to retrieve
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->owner] the wallet address to fetch orders for
         * @return {Order[]} a list of [order structures](https://docs.ccxt.com/#/?id=order-structure)
         */
        $this->load_markets();
        $market = null;
        if ($symbol !== null) {
            $market = $this->market($symbol);
        }
        $owner = null;
        list($owner, $params) = $this->ensure_owner_address($params);
        $request = array(
            'owner' => $owner,
        );
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        $response = $this->publicGetApiV1AccountOwnerOrders ($this->extend($request, $params));
        $rawOrders = $this->safe_list($response, 'orders', $response);
        $parsedOrders = $this->parse_orders($rawOrders, $market, $since, $limit);
        return $this->filter_by_symbol_since_limit($parsedOrders, $symbol, $since, $limit);
    }

    public function fetch_open_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetch all unfilled currently open $orders
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $symbol unified market $symbol
         * @param {int} [$since] the earliest time in ms to fetch open $orders for
         * @param {int} [$limit] the maximum number of open order structures to retrieve
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->owner] the wallet address to fetch $orders for
         * @return {Order[]} a list of [order structures](https://docs.ccxt.com/#/?id=order-structure)
         */
        $orders = $this->fetch_orders($symbol, $since, $limit, $params);
        return $this->filter_by($orders, 'status', 'open');
    }

    public function fetch_closed_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetches information on multiple closed $orders made by the user
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $symbol unified market $symbol of the market $orders were made in
         * @param {int} [$since] the earliest time in ms to fetch $orders for
         * @param {int} [$limit] the maximum number of order structures to retrieve
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->owner] the wallet address to fetch $orders for
         * @return {Order[]} a list of [order structures](https://docs.ccxt.com/#/?id=order-structure)
         */
        $orders = $this->fetch_orders($symbol, $since, $limit, $params);
        return $this->filter_by($orders, 'status', 'closed');
    }

    public function fetch_canceled_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetches information on multiple canceled $orders made by the user
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $symbol unified market $symbol of the market $orders were made in
         * @param {int} [$since] the earliest time in ms to fetch $orders for
         * @param {int} [$limit] the maximum number of order structures to retrieve
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->owner] the wallet address to fetch $orders for
         * @return {Order[]} a list of [order structures](https://docs.ccxt.com/#/?id=order-structure)
         */
        $orders = $this->fetch_orders($symbol, $since, $limit, $params);
        return $this->filter_by($orders, 'status', 'canceled');
    }

    public function fetch_balance($params = array ()): array {
        /**
         * query for $balance and get the amount of funds available for trading or funds locked in orders
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->owner] the wallet address to query $balance for
         * @return {array} a [$balance structure](https://docs.ccxt.com/#/?id=$balance-structure)
         */
        $this->load_markets();
        $owner = null;
        list($owner, $params) = $this->ensure_owner_address($params);
        $ownerAddress = $this->address_with0x_prefix($owner);
        $result = array(
            'info' => array(),
            'timestamp' => null,
            'datetime' => null,
        );
        $currencies = array();
        $marketValues = is_array($this->markets) ? array_values($this->markets) : array();
        for ($i = 0; $i < count($marketValues); $i++) {
            $market = $marketValues[$i];
            $baseCode = $this->safe_string($market, 'base');
            $baseId = $this->safe_string_lower($market, 'baseId');
            $marketInfo = $this->safe_value($market, 'info', array());
            $baseInfo = $this->safe_value($marketInfo, 'base', array());
            $decimals = $this->safe_string($baseInfo, 'decimals');
            if (($baseCode !== null) && ($baseId !== null) && ($decimals !== null)) {
                if (!(is_array($currencies) && array_key_exists($baseCode, $currencies))) {
                    $currencies[$baseCode] = array( 'id' => $baseId, 'decimals' => $decimals );
                }
            }
        }
        $currencyCodes = is_array($currencies) ? array_keys($currencies) : array();
        for ($i = 0; $i < count($currencyCodes); $i++) {
            $code = $currencyCodes[$i];
            $currencyInfo = $currencies[$code];
            $tokenAddress = $this->safe_string($currencyInfo, 'id');
            $decimals = $this->safe_string($currencyInfo, 'decimals');
            try {
                $balanceRaw = $this->fetch_erc20_balance($tokenAddress, $ownerAddress);
                $balanceString = $this->convert_token_amount($balanceRaw, $decimals);
                $balance = $this->parse_number($balanceString);
                $result[$code] = array(
                    'free' => $balance,
                    'used' => 0, // CoW doesn't lock funds, orders are intent-based
                    'total' => $balance,
                );
            } catch (Exception $e) {
                $result[$code] = array(
                    'free' => 0,
                    'used' => 0,
                    'total' => 0,
                );
            }
        }
        return $this->safe_balance($result);
    }

    public function fetch_my_trades(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): array {
        /**
         * fetch all $trades made by the user
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $symbol unified $market $symbol
         * @param {int} [$since] the earliest time in ms to fetch $trades for
         * @param {int} [$limit] the maximum number of $trades structures to retrieve
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->owner] the wallet address to fetch $trades for
         * @return {Trade[]} a list of [trade structures](https://docs.ccxt.com/#/?id=trade-structure)
         */
        $this->load_markets();
        $market = null;
        if ($symbol !== null) {
            $market = $this->market($symbol);
        }
        $owner = null;
        list($owner, $params) = $this->ensure_owner_address($params);
        $request = array(
            'owner' => $owner,
        );
        if ($limit !== null) {
            $request['limit'] = $limit;
        }
        if ($since !== null) {
            $request['minTimestamp'] = $since;
        }
        $response = $this->publicGetApiV1Trades ($this->extend($request, $params));
        $trades = $this->parse_trades($response, $market, $since, $limit);
        return $this->filter_by_symbol_since_limit($trades, $symbol, $since, $limit);
    }

    public function create_order(string $symbol, string $type, string $side, float $amount, ?float $price = null, $params = array ()): array {
        /**
         * create a trade order on CoW Protocol
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $symbol unified $symbol of the $market to create an order in
         * @param {string} $type 'market' or 'limit'
         * @param {string} $side 'buy' or 'sell'
         * @param {float} $amount how much of currency you want to trade in units of base currency
         * @param {float} [$price] the $price at which the order is to be fulfilled, in units of the $quote currency, ignored in $market orders
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {int} [$params->validFor] order validity duration in seconds (default 30)
         * @param {int} [$params->validTo] unix timestamp when the order expires
         * @param {bool} [$params->partiallyFillable] whether the order can be partially filled (default false)
         * @param {string} [$params->appData] app data for the order (32-byte hex string)
         * @param {string} [$params->receiver] the address to receive the bought tokens (defaults to sender)
         * @param {string} [$params->from] the address placing the order (defaults to walletAddress)
         * @param {array} [$params->quoteRequest] override parameters for the $quote request
         * @return {array} an [order structure](https://docs.ccxt.com/#/?id=order-structure)
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $this->check_required_credentials();
        if (($this->privateKey === null) || ($this->privateKey === '')) {
            throw new AuthenticationError($this->id . ' createOrder() requires exchange.privateKey to be set');
        }
        $owner = null;
        list($owner, $params) = $this->ensure_owner_address($params);
        $receiverParam = $this->safe_string_lower($params, 'receiver', $owner);
        $fromParam = $this->safe_string_lower($params, 'from', $owner);
        $params = $this->omit($params, array( 'receiver', 'from' ));
        $defaultKind = ($side === 'sell') ? 'sell' : 'buy';
        $kind = $this->safe_string_lower($params, 'kind', $defaultKind);
        if (($type !== 'limit') && ($type !== 'market')) {
            throw new NotSupported($this->id . ' createOrder() supports $market and limit order types');
        }
        if (($type === 'limit') && ($price === null)) {
            throw new ArgumentsRequired($this->id . ' createOrder() requires a $price argument for limit orders');
        }
        $marketInfo = $this->safe_value($market, 'info', array());
        $baseInfo = $this->safe_value($marketInfo, 'base', array());
        $quoteInfo = $this->safe_value($marketInfo, 'quote', array());
        $baseDecimals = $this->safe_string($baseInfo, 'decimals');
        $quoteDecimals = $this->safe_string($quoteInfo, 'decimals');
        $partiallyFillable = $this->safe_bool($params, 'partiallyFillable', false);
        $validFor = $this->safe_integer($params, 'validFor', $this->safe_integer($this->options, 'defaultValidFor', 30));
        $currentSeconds = $this->seconds();
        $validTo = $this->safe_integer($params, 'validTo', $currentSeconds . $validFor);
        $appData = $this->safe_string($params, 'appData', $this->safe_string($this->options, 'defaultAppData'));
        $quoteRequestOverrides = $this->safe_dict($params, 'quoteRequest');
        $params = $this->omit($params, array( 'kind', 'partiallyFillable', 'validFor', 'validTo', 'appData', 'quoteRequest' ));
        $isSellOrder = ($kind === 'sell');
        $sellToken = $isSellOrder ? $this->safe_string_lower($market, 'baseId') : $this->safe_string_lower($market, 'quoteId');
        $buyToken = $isSellOrder ? $this->safe_string_lower($market, 'quoteId') : $this->safe_string_lower($market, 'baseId');
        $sellTokenDecimals = $isSellOrder ? $baseDecimals : $quoteDecimals;
        $buyTokenDecimals = $isSellOrder ? $quoteDecimals : $baseDecimals;
        $amountString = $this->number_to_string($amount);
        $sellAmountRaw = null;
        $buyAmountRaw = null;
        if ($isSellOrder) {
            $sellAmountRaw = $this->amount_to_token_amount($amountString, $sellTokenDecimals);
        } else {
            $buyAmountRaw = $this->amount_to_token_amount($amountString, $buyTokenDecimals);
        }
        $receiverAddress = $this->address_with0x_prefix($receiverParam);
        $fromAddress = $this->address_with0x_prefix($fromParam);
        $quoteRequest = $this->extend(array(
            'sellToken' => $this->address_with0x_prefix($sellToken),
            'buyToken' => $this->address_with0x_prefix($buyToken),
            'receiver' => $receiverAddress,
            'from' => $fromAddress,
            'kind' => $kind,
            'validTo' => $validTo,
            'partiallyFillable' => $partiallyFillable,
            'sellTokenBalance' => 'erc20',
            'buyTokenBalance' => 'erc20',
        ), $quoteRequestOverrides);
        if ($isSellOrder) {
            $quoteRequest['sellAmountBeforeFee'] = $this->safe_string($quoteRequest, 'sellAmountBeforeFee', $sellAmountRaw);
            if ($type === 'limit') {
                $priceString = $this->number_to_string($price);
                $costDecimal = Precise::string_mul($amountString, $priceString);
                $buyAmountRawLimit = $this->amount_to_token_amount($costDecimal, $buyTokenDecimals);
                $quoteRequest['buyAmountAfterFee'] = $this->safe_string($quoteRequest, 'buyAmountAfterFee', $buyAmountRawLimit);
            }
        } else {
            $quoteRequest['buyAmountAfterFee'] = $this->safe_string($quoteRequest, 'buyAmountAfterFee', $buyAmountRaw);
            if ($type === 'limit') {
                $priceString = $this->number_to_string($price);
                $costDecimal = Precise::string_mul($amountString, $priceString);
                $sellAmountRawLimit = $this->amount_to_token_amount($costDecimal, $sellTokenDecimals);
                $quoteRequest['sellAmountBeforeFee'] = $this->safe_string($quoteRequest, 'sellAmountBeforeFee', $sellAmountRawLimit);
            }
        }
        $quoteResponse = $this->publicPostApiV1Quote ($quoteRequest);
        $quote = $this->safe_dict($quoteResponse, 'quote', $quoteResponse);
        $orderBody = array(
            'sellToken' => $this->address_with0x_prefix($this->safe_string($quote, 'sellToken', $sellToken)),
            'buyToken' => $this->address_with0x_prefix($this->safe_string($quote, 'buyToken', $buyToken)),
            'receiver' => $this->address_with0x_prefix($this->safe_string($quote, 'receiver', $receiverParam)),
            'sellAmount' => $this->safe_string($quote, 'sellAmount', $sellAmountRaw),
            'buyAmount' => $this->safe_string($quote, 'buyAmount', $this->safe_string($quoteRequest, 'buyAmountAfterFee')),
            'validTo' => $this->safe_integer($quote, 'validTo', $validTo),
            'appData' => $this->safe_string($quote, 'appData', $appData),
            'feeAmount' => '0', // CoW Protocol requires fee to be zero (fee is already included in $sellAmount)
            'kind' => $this->safe_string_lower($quote, 'kind', $kind),
            'partiallyFillable' => $this->safe_bool($quote, 'partiallyFillable', $partiallyFillable),
            'sellTokenBalance' => $this->safe_string_lower($quote, 'sellTokenBalance', 'erc20'),
            'buyTokenBalance' => $this->safe_string_lower($quote, 'buyTokenBalance', 'erc20'),
        );
        $signingScheme = $this->safe_string_lower($quote, 'signingScheme', 'eip712');
        $orderBody['signingScheme'] = $signingScheme;
        $orderBody['signature'] = $this->sign_order_payload($orderBody, $signingScheme);
        $signerAddr = $this->derive_wallet_address_from_private_key();
        $orderBody['from'] = strtolower($this->address_with0x_prefix($signerAddr));
        $autoApprove = $this->safe_bool($this->options, 'autoApprove', true);
        if ($autoApprove) {
            $sellTokenAddress = $this->safe_string($orderBody, 'sellToken');
            if ($sellTokenAddress !== null) {
                $vaultRelayer = $this->get_vault_relayer_option();
                $sellAmount = $this->safe_string($orderBody, 'sellAmount', '0');
                $feeAmount = $this->safe_string($orderBody, 'feeAmount', '0');
                $requiredAmount = Precise::string_add($sellAmount, $feeAmount);
                try {
                    $currentAllowance = $this->check_erc20_allowance($sellTokenAddress, $this->hex_with0x_prefix($signerAddr), $vaultRelayer);
                    if (Precise::string_lt($currentAllowance, $requiredAmount)) {
                        $this->log('Insufficient allowance detected. Approving VaultRelayer...');
                        $approvalResult = $this->approve_erc20($sellTokenAddress, $vaultRelayer);
                        $this->log('Approval transaction:', $approvalResult['txHash']);
                        $this->sleep(5000);
                    }
                } catch (Exception $e) {
                    $message = $this->safe_string($e, 'message', $this->json($e));
                    throw new ExchangeError($this->id . ' createOrder() failed to ensure allowance => ' . $message);
                }
            }
        }
        $response = $this->publicPostApiV1Orders ($orderBody);
        $uid = $this->safe_string_2($response, 'orderUid', 'uid');
        $parsed = $this->parse_order($this->extend(array(), $orderBody, array( 'uid' => $uid, 'info' => $response, 'status' => 'open' )), $market);
        return $this->extend($parsed, array( 'info' => $response ));
    }

    public function cancel_order(string $id, ?string $symbol = null, $params = array ()): array {
        /**
         * cancels an open order
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $id order $id (UID)
         * @param {string} $symbol unified $symbol of the $market the order was made in
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->signingScheme] 'eip712' or 'ethsign' (default 'eip712')
         * @return {array} An [order structure](https://docs.ccxt.com/#/?$id=order-structure)
         */
        $this->load_markets();
        $this->check_required_credentials();
        if (($this->privateKey === null) || ($this->privateKey === '')) {
            throw new AuthenticationError($this->id . ' cancelOrder() requires exchange.privateKey to be set');
        }
        $owner = null;
        list($owner, $params) = $this->ensure_owner_address($params);
        $signingScheme = $this->safe_string_lower($params, 'signingScheme', 'eip712');
        $params = $this->omit($params, array( 'signingScheme' ));
        $orderUids = array( $id );
        $requestBody = array(
            'orderUids' => $orderUids,
            'signature' => $this->sign_order_cancellation($orderUids, $signingScheme),
            'signingScheme' => $signingScheme,
        );
        $headers = array( 'Content-Type' => 'application/json' );
        $response = $this->request('api/v1/orders', 'public', 'DELETE', $params, $headers, $this->json($requestBody));
        $market = ($symbol !== null) ? $this->market($symbol) : null;
        return $this->parse_order(array( 'uid' => $id, 'status' => 'canceled', 'info' => $response, 'owner' => $owner ), $market);
    }

    public function cancel_all_orders(?string $symbol = null, $params = array ()): array {
        /**
         * cancel all open orders
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $symbol unified market $symbol, only orders in the market of this $symbol are cancelled when $symbol is not null
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {string} [$params->owner] the wallet address to cancel orders for
         * @param {string} [$params->signingScheme] 'eip712' or 'ethsign' (default 'eip712')
         * @return {array[]} a list of [$order structures](https://docs.ccxt.com/#/?id=$order-structure)
         */
        $this->load_markets();
        $openOrders = $this->fetch_open_orders($symbol, null, null, $params);
        if (strlen($openOrders) === 0) {
            return array();
        }
        $results = array();
        for ($i = 0; $i < count($openOrders); $i++) {
            $order = $openOrders[$i];
            $orderId = $this->safe_string($order, 'id');
            if ($orderId !== null) {
                try {
                    $result = $this->cancel_order($orderId, $symbol, $params);
                    $results[] = $result;
                } catch (Exception $e) {
                    $results[] = $this->extend($order, array( 'status' => 'failed', 'info' => $e ));
                }
            }
        }
        return $results;
    }

    public function ensure_owner_address(array $params = array ()): array {
        $owner = $this->safe_string_lower_2($params, 'owner', 'walletAddress');
        $modifiedParams = $this->omit($params, array( 'owner', 'walletAddress' ));
        $derivedOwner = $this->derive_wallet_address_from_private_key();
        if ($owner === null) {
            $optionOwner = $this->safe_string_lower($this->options, 'walletAddress');
            if ($optionOwner !== null) {
                $owner = $optionOwner;
            } elseif (($this->walletAddress !== null) && (gettype($this->walletAddress) === 'string') && ($this->walletAddress !== '')) {
                $owner = strtolower($this->walletAddress);
            } elseif ($derivedOwner !== null) {
                $owner = $derivedOwner;
            }
        }
        if (($owner !== null) && str_starts_with(!$owner, '0x')) {
            $owner = '0x' . $owner;
        }
        if (($derivedOwner !== null) && ($owner !== null) && (strtolower($owner) !== $derivedOwner)) {
            throw new AuthenticationError($this->id . ' walletAddress mismatch between provided $owner and private key');
        }
        if ($owner === null) {
            throw new ArgumentsRequired($this->id . ' requires a wallet address; set exchange.walletAddress, exchange.options["walletAddress"] or provide $params["owner"]');
        }
        return array( strtolower($owner), $modifiedParams );
    }

    public function hex_with0x_prefix(?string $value): ?string {
        if ($value === null) {
            return $value;
        }
        return str_starts_with($value, '0x') ? $value : ('0x' . $value);
    }

    public function address_with0x_prefix(?string $value): ?string {
        return $this->hex_with0x_prefix($value);
    }

    public function normalize_private_key(?string $privateKey): ?string {
        if ($privateKey === null) {
            return $privateKey;
        }
        return $this->hex_with0x_prefix($privateKey);
    }

    public function derive_wallet_address_from_private_key(): ?string {
        $normalizedKey = $this->normalize_private_key($this->privateKey);
        if (($normalizedKey === null) || ($normalizedKey === '')) {
            return null;
        }
        $keyHex = $this->remove0x_prefix($normalizedKey);
        if (strlen($keyHex) !== 64) {
            throw new AuthenticationError($this->id . ' privateKey must be a 32-byte hex string');
        }
        $privateKeyBytes = $this->base16_to_binary($keyHex);
        $publicKey = secp256k1.getPublicKey ($privateKeyBytes, false);
        $hashBytes = keccak (mb_substr($publicKey, 1));
        $addressBytes = mb_substr($hashBytes, -20);
        $address = '0x' . bin2hex($addressBytes);
        return strtolower($address);
    }

    public function amount_to_token_amount(?string $amountString, ?string $decimals): ?string {
        if (($amountString === null) || ($decimals === null)) {
            return null;
        }
        $decimalsString = $this->number_to_string($decimals);
        $precision = $this->parse_precision($decimalsString);
        return Precise::string_div($amountString, $precision);
    }

    public function get_chain_id_option() {
        $network = $this->safe_string($this->options, 'network', 'mainnet');
        $chains = $this->safe_value($this->options, 'chainIds', array());
        $chainId = $this->safe_integer($chains, $network);
        if ($chainId === null) {
            throw new ExchangeError($this->id . ' unsupported $network ' . $network . ' for chain id resolution');
        }
        return $chainId;
    }

    public function get_verifying_contract_option() {
        $network = $this->safe_string($this->options, 'network', 'mainnet');
        $contracts = $this->safe_value($this->options, 'verifyingContracts', array());
        $verifyingContract = $this->safe_string($contracts, $network);
        if ($verifyingContract === null) {
            throw new ExchangeError($this->id . ' unsupported $network ' . $network . ' for verifying contract resolution');
        }
        return $this->hex_with0x_prefix($verifyingContract);
    }

    public function get_vault_relayer_option() {
        $network = $this->safe_string($this->options, 'network', 'mainnet');
        $relayers = $this->safe_value($this->options, 'vaultRelayers', array());
        $vaultRelayer = $this->safe_string($relayers, $network);
        if ($vaultRelayer === null) {
            throw new ExchangeError($this->id . ' unsupported $network ' . $network . ' for vault relayer resolution');
        }
        return $this->hex_with0x_prefix($vaultRelayer);
    }

    public function get_rpc_url_option() {
        $network = $this->safe_string($this->options, 'network', 'mainnet');
        $rpcUrls = $this->safe_value($this->options, 'rpcUrls', array());
        return $this->safe_string($rpcUrls, $network);
    }

    public function fetch_erc20_balance(?string $tokenAddress, ?string $ownerAddress) {
        $rpcUrl = $this->get_rpc_url_option();
        if ($rpcUrl === null) {
            throw new ExchangeError($this->id . ' fetchERC20Balance() requires rpcUrls[' . $this->options['network'] . '] to be configured');
        }
        $ownerPadded = $this->remove0x_prefix($ownerAddress).padStart (64, '0');
        // ERC20 balanceOf(address) = 0x70a08231
        $data = '0x70a08231' . $ownerPadded;
        $request = array(
            'jsonrpc' => '2.0',
            'method' => 'eth_call',
            'params' => array(
                array(
                    'to' => $tokenAddress,
                    'data' => $data,
                ),
                'latest',
            ),
            'id' => 1,
        );
        $response = $this->fetch($rpcUrl, 'POST', array( 'Content-Type' => 'application/json' ), $this->json($request));
        $result = $this->safe_string($response, 'result', '0x0');
        $errorResult = $this->safe_value($response, 'error');
        if ($errorResult !== null) {
            throw new ExchangeError($this->id . ' fetchERC20Balance() RPC error => ' . $this->json($errorResult));
        }
        if ($result === '0x') {
            return '0';
        }
        $hexValue = $this->remove0x_prefix($result);
        if ($hexValue === '') {
            return '0';
        }
        return BigInt ('0x' . (string) $hexValue);
    }

    public function check_erc20_allowance(?string $tokenAddress, ?string $ownerAddress, ?string $spenderAddress) {
        $rpcUrl = $this->get_rpc_url_option();
        if ($rpcUrl === null) {
            throw new ExchangeError($this->id . ' checkERC20Allowance() requires rpcUrls[' . $this->options['network'] . '] to be configured');
        }
        $ownerPadded = $this->remove0x_prefix($ownerAddress).padStart (64, '0');
        $spenderPadded = $this->remove0x_prefix($spenderAddress).padStart (64, '0');
        $data = '0xdd62ed3e' . $ownerPadded . $spenderPadded;
        $request = array(
            'jsonrpc' => '2.0',
            'method' => 'eth_call',
            'params' => array(
                array(
                    'to' => $tokenAddress,
                    'data' => $data,
                ),
                'latest',
            ),
            'id' => 1,
        );
        $response = $this->fetch($rpcUrl, 'POST', array( 'Content-Type' => 'application/json' ), $this->json($request));
        $result = $this->safe_string($response, 'result', '0');
        if ($result === '0') {
            $errorResult = $this->safe_value($response, 'error');
            if ($errorResult !== null) {
                throw new ExchangeError($this->id . ' checkERC20Allowance() failed to fetch allowance => ' . $this->json($response));
            }
        }
        return $result;
    }

    public function approve_erc20(?string $tokenAddress, ?string $spenderAddress, ?string $amount = null) {
        $rpcUrl = $this->get_rpc_url_option();
        if ($rpcUrl === null) {
            throw new ExchangeError($this->id . ' approveERC20() requires rpcUrls[' . $this->options['network'] . '] to be configured');
        }
        $privateKey = $this->normalize_private_key($this->privateKey);
        $ownerAddress = $this->derive_wallet_address_from_private_key();
        $approvalAmount = ($amount !== null) ? $amount : '0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff';
        $spenderPadded = $this->remove0x_prefix($spenderAddress).padStart (64, '0');
        $amountHex = $approvalAmount;
        if (str_starts_with($amountHex, '0x')) {
            $amountHex = '0x' . $this->remove0x_prefix($amountHex).padStart (64, '0');
        } else {
            $numericValue = intval($amountHex);
            $amountHex = '0x' . $numericValue->toString (16).padStart (64, '0');
        }
        $data = '0x095ea7b3' . $spenderPadded . $this->remove0x_prefix($amountHex);
        $nonceRequest = array(
            'jsonrpc' => '2.0',
            'method' => 'eth_getTransactionCount',
            'params' => array( $this->hex_with0x_prefix($ownerAddress), 'latest' ),
            'id' => 2,
        );
        $nonceResponse = $this->fetch($rpcUrl, 'POST', array( 'Content-Type' => 'application/json' ), $this->json($nonceRequest));
        $nonce = $this->safe_string($nonceResponse, 'result');
        $gasPriceRequest = array(
            'jsonrpc' => '2.0',
            'method' => 'eth_gasPrice',
            'params' => array(),
            'id' => 3,
        );
        $gasPriceResponse = $this->fetch($rpcUrl, 'POST', array( 'Content-Type' => 'application/json' ), $this->json($gasPriceRequest));
        $gasPrice = $this->safe_string($gasPriceResponse, 'result');
        $chainId = $this->get_chain_id_option();
        $tx = array(
            'nonce' => $nonce,
            'gasPrice' => $gasPrice,
            'gasLimit' => '0x186a0', // 100000 in hex
            'to' => $tokenAddress,
            'value' => '0x0',
            'data' => $data,
            'chainId' => $chainId,
        );
        $txFields = [
            $tx['nonce'],
            $tx['gasPrice'],
            $tx['gasLimit'],
            $tx['to'],
            $tx['value'],
            $tx['data'],
            '0x' . $chainId->toString (16),
            '0x',
            '0x',
        ];
        $rlpEncoded = $this->encode_rlp($txFields);
        $txHash = '0x' . bin2hex(keccak ($this->base16_to_binary($this->remove0x_prefix($rlpEncoded))));
        $privateKeyBytes = $this->base16_to_binary($this->remove0x_prefix($privateKey));
        $hashBytes = $this->base16_to_binary($this->remove0x_prefix($txHash));
        $signature = secp256k1.sign ($hashBytes, $privateKeyBytes);
        $compact = $signature->toCompactHex ();
        $r = mb_substr($compact, 0, 64 - 0);
        $s = mb_substr($compact, 64);
        $recovery = $signature->recovery;
        $v = ($chainId * 2) + 35 . $recovery;
        $signedTxFields = [
            $tx['nonce'],
            $tx['gasPrice'],
            $tx['gasLimit'],
            $tx['to'],
            $tx['value'],
            $tx['data'],
            '0x' . $v->toString (16),
            '0x' . $r,
            '0x' . $s,
        ];
        $signedRlp = $this->encode_rlp($signedTxFields);
        $broadcastRequest = array(
            'jsonrpc' => '2.0',
            'method' => 'eth_sendRawTransaction',
            'params' => array( $signedRlp ),
            'id' => 4,
        );
        $broadcastResponse = $this->fetch($rpcUrl, 'POST', array( 'Content-Type' => 'application/json' ), $this->json($broadcastRequest));
        $txHashResult = $this->safe_string($broadcastResponse, 'result');
        $error = $this->safe_value($broadcastResponse, 'error');
        if ($error !== null) {
            throw new ExchangeError($this->id . ' approveERC20() failed => ' . $this->json($error));
        }
        return array(
            'txHash' => $txHashResult,
            'token' => $tokenAddress,
            'spender' => $spenderAddress,
            'amount' => $approvalAmount,
        );
    }

    public function encode_rlp_item(string $value): string {
        $hex = $value;
        if (str_starts_with(!$hex, '0x')) {
            $hex = '0x' . $hex;
        }
        $hex = strtolower($this->remove0x_prefix($hex));
        while (strlen($hex) > 1 && $hex[0] === '0') {
            $hex = mb_substr($hex, 1);
        }
        if (strlen($hex) === 0) {
            $hex = '0';
        }
        if (strlen(fmod($hex), 2) !== 0) {
            $hex = '0' . $hex;
        }
        if ($hex === '00' || $hex === '') {
            return '80';
        }
        $length = strlen($hex) / 2;
        if ($length === 1 && intval($hex, 16) < 128) {
            return $hex;
        }
        if ($length < 56) {
            return (128 . $length).toString (16).padStart (2, '0') . $hex;
        }
        $lengthHex = $length->toString (16);
        $lengthOfLength = (int) ceil(strlen($lengthHex) / 2);
        $paddedLengthHex = str_pad($lengthHex, $lengthOfLength * 2, '0', STR_PAD_LEFT);
        return (183 . $lengthOfLength).toString (16) . $paddedLengthHex . $hex;
    }

    public function encode_rlp(array $fields): string {
        $encoded = array();
        for ($i = 0; $i < count($fields); $i++) {
            $encoded[] = $this->encode_rlp_item($fields[$i]);
        }
        $concatenated = implode('', $encoded);
        $totalLength = strlen($concatenated) / 2;
        if ($totalLength < 56) {
            return '0x' . (192 . $totalLength).toString (16).padStart (2, '0') . $concatenated;
        }
        $lengthHex = $totalLength->toString (16);
        $lengthOfLength = (int) ceil(strlen($lengthHex) / 2);
        $paddedLengthHex = str_pad($lengthHex, $lengthOfLength * 2, '0', STR_PAD_LEFT);
        return '0x' . (247 . $lengthOfLength).toString (16) . $paddedLengthHex . $concatenated;
    }

    public function compute_typed_data_digest(array $domain, array $types, array $message) {
        $encoder = TypedDataEncoder;
        if (is_callable($encoder->hash)) {
            return $encoder->hash ($domain, $types, $message);
        }
        $encoded = $encoder->encode ($domain, $types, $message);
        $encodedBinary = $this->base16_to_binary(mb_substr($encoded, 2));
        $digestBytes = keccak ($encodedBinary);
        return '0x' . bin2hex($digestBytes);
    }

    public function hash_ethereum_signed_message(?string $messageHex) {
        if ($messageHex === null) {
            return null;
        }
        $binaryMessage = $this->base16_to_binary($this->remove0x_prefix($messageHex));
        if (strlen($binaryMessage) !== 32) {
            throw new ExchangeError($this->id . ' hashEthereumSignedMessage() requires a 32-byte digest hex string');
        }
        $messageLength = $this->binary_length($binaryMessage);
        // eslint-disable-next-line quotes
        $prefixString = "\x19Ethereum Signed Message:\n" . $this->number_to_string($messageLength);
        $prefixBinary = $this->encode($prefixString);
        $prefixed = $this->binary_concat($prefixBinary, $binaryMessage);
        $digestBytes = keccak ($prefixed);
        return '0x' . bin2hex($digestBytes);
    }

    public function sign_digest(?string $digest, ?string $privateKey, bool $usePersonalSign = false) {
        $normalizedKey = $this->normalize_private_key($privateKey);
        if ($digest === null || $normalizedKey === null) {
            return null;
        }
        $hashToSign = $digest;
        if ($usePersonalSign) {
            $hashToSign = $this->hash_ethereum_signed_message($digest);
        }
        $digestBytes = $this->base16_to_binary($this->remove0x_prefix($hashToSign));
        $privateKeyBytes = $this->base16_to_binary($this->remove0x_prefix($normalizedKey));
        $signature = secp256k1.sign ($digestBytes, $privateKeyBytes);
        $compact = $signature->toCompactHex ();
        $recovery = $signature->recovery;
        $r = mb_substr($compact, 0, 64 - 0);
        $s = mb_substr($compact, 64);
        $vValue = $recovery + 27;
        $vHex = $vValue->toString (16).padStart (2, '0');
        return '0x' . $r . $s . $vHex;
    }

    public function sign_order_payload(array $order, ?string $signingScheme = 'eip712') {
        $privateKey = $this->normalize_private_key($this->privateKey);
        $chainId = $this->get_chain_id_option();
        $verifyingContract = $this->get_verifying_contract_option();
        $domain = array(
            'name' => 'Gnosis Protocol',
            'version' => 'v2',
            'chainId' => $chainId,
            'verifyingContract' => $verifyingContract,
        );
        $receiverAddress = $this->safe_string($order, 'receiver');
        $normalizedReceiver = '0x0000000000000000000000000000000000000000';
        if ($receiverAddress !== null) {
            $normalizedReceiver = getAddress ($this->hex_with0x_prefix($receiverAddress));
        }
        $message = array(
            'sellToken' => getAddress ($this->hex_with0x_prefix($order['sellToken'])),
            'buyToken' => getAddress ($this->hex_with0x_prefix($order['buyToken'])),
            'receiver' => $normalizedReceiver,
            'sellAmount' => $this->safe_string($order, 'sellAmount'),
            'buyAmount' => $this->safe_string($order, 'buyAmount'),
            'validTo' => $this->safe_integer($order, 'validTo'),
            'appData' => $this->hex_with0x_prefix($this->safe_string($order, 'appData')),
            'feeAmount' => $this->safe_string($order, 'feeAmount', '0'),
            'kind' => $this->safe_string_lower($order, 'kind'),
            'partiallyFillable' => $this->safe_bool($order, 'partiallyFillable', false),
            'sellTokenBalance' => $this->safe_string_lower($order, 'sellTokenBalance', 'erc20'),
            'buyTokenBalance' => $this->safe_string_lower($order, 'buyTokenBalance', 'erc20'),
        );
        $types = array(
            'Order' => array(
                array( 'name' => 'sellToken', 'type' => 'address' ),
                array( 'name' => 'buyToken', 'type' => 'address' ),
                array( 'name' => 'receiver', 'type' => 'address' ),
                array( 'name' => 'sellAmount', 'type' => 'uint256' ),
                array( 'name' => 'buyAmount', 'type' => 'uint256' ),
                array( 'name' => 'validTo', 'type' => 'uint32' ),
                array( 'name' => 'appData', 'type' => 'bytes32' ),
                array( 'name' => 'feeAmount', 'type' => 'uint256' ),
                array( 'name' => 'kind', 'type' => 'string' ),
                array( 'name' => 'partiallyFillable', 'type' => 'bool' ),
                array( 'name' => 'sellTokenBalance', 'type' => 'string' ),
                array( 'name' => 'buyTokenBalance', 'type' => 'string' ),
            ),
        );
        $typedDataEncoder = new TypedDataEncoder ($types);
        $domainSeparator = TypedDataEncoder.hashDomain ($domain);
        $structHash = $typedDataEncoder->hash ($message);
        $prefix = '0x1901';
        $encoded = $prefix . mb_substr($domainSeparator, 2) . mb_substr($structHash, 2);
        $digest = '0x' . bin2hex(keccak ($this->base16_to_binary(mb_substr($encoded, 2))));
        $usePersonalSign = ($signingScheme === 'ethsign');
        return $this->sign_digest($digest, $privateKey, $usePersonalSign);
    }

    public function sign_order_cancellation(array $orderUids, ?string $signingScheme = 'eip712') {
        $privateKey = $this->normalize_private_key($this->privateKey);
        $chainId = $this->get_chain_id_option();
        $verifyingContract = $this->get_verifying_contract_option();
        $domain = array(
            'name' => 'Gnosis Protocol',
            'version' => 'v2',
            'chainId' => $chainId,
            'verifyingContract' => $verifyingContract,
        );
        $typeString = 'OrderCancellations(bytesarray() $orderUids)';
        $typeHash = '0x' . bin2hex(keccak ($typeString));
        $concatenatedHashes = '';
        for ($i = 0; $i < count($orderUids); $i++) {
            $uid = $this->hex_with0x_prefix($orderUids[$i]);
            $uidBytes = $this->base16_to_binary(mb_substr($uid, 2));
            $uidHash = keccak ($uidBytes);
            $concatenatedHashes .= bin2hex($uidHash);
        }
        $arrayHash = '0x' . bin2hex(keccak ($this->base16_to_binary($concatenatedHashes)));
        $structHashInput = mb_substr($typeHash, 2) . mb_substr($arrayHash, 2);
        $structHash = '0x' . bin2hex(keccak ($this->base16_to_binary($structHashInput)));
        $domainSeparator = TypedDataEncoder.hashDomain ($domain);
        $prefix = '0x1901';
        $encoded = $prefix . mb_substr($domainSeparator, 2) . mb_substr($structHash, 2);
        $digest = '0x' . bin2hex(keccak ($this->base16_to_binary(mb_substr($encoded, 2))));
        if ($signingScheme === 'ethsign') {
            $prefixedDigest = $this->hash_ethereum_signed_message($digest);
            return $this->sign_digest($prefixedDigest, $privateKey, false);
        } else {
            return $this->sign_digest($digest, $privateKey, false);
        }
    }

    public function compare_quote_with_other_exchanges(?string $symbol, float $amount, array $otherExchanges = [], $params = array ()) {
        /**
         * get a $quote from CoW Protocol and compare it with quotes from other exchanges
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $symbol unified $market $symbol
         * @param {float} $amount the $amount of base currency to trade
         * @param {array[]} $otherExchanges array of $exchange instances to compare quotes with
         * @param {array} [$params] extra parameters specific to the $exchange API endpoint
         * @param {string} [$params->receiver] the address to receive the bought tokens
         * @param {string} [$params->from] the address placing the order
         * @param {int} [$params->validFor] $quote validity duration in seconds
         * @return {array} a $comparison object with CoW $quote and other $exchange quotes
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $marketInfo = $this->safe_value($market, 'info', array());
        $baseInfo = $this->safe_value($marketInfo, 'base', array());
        $quoteInfo = $this->safe_value($marketInfo, 'quote', array());
        $baseDecimals = $this->safe_string($baseInfo, 'decimals');
        $quoteDecimals = $this->safe_string($quoteInfo, 'decimals');
        $owner = null;
        list($owner, $params) = $this->ensure_owner_address($params);
        $receiverParam = $this->safe_string_lower($params, 'receiver', $owner);
        $fromParam = $this->safe_string_lower($params, 'from', $owner);
        $amountString = $this->number_to_string($amount);
        $sellAmountRaw = $this->amount_to_token_amount($amountString, $baseDecimals);
        $nowSeconds = $this->seconds();
        $validFor = $this->safe_integer($params, 'validFor', $this->safe_integer($this->options, 'defaultValidFor', 30));
        $validTo = $this->safe_integer($params, 'validTo', $nowSeconds . $validFor);
        $params = $this->omit($params, array( 'validFor', 'validTo', 'receiver', 'from' ));
        $quoteRequest = $this->extend(array(
            'sellToken' => $this->address_with0x_prefix($market['baseId']),
            'buyToken' => $this->address_with0x_prefix($market['quoteId']),
            'sellAmountBeforeFee' => $sellAmountRaw,
            'receiver' => $this->address_with0x_prefix($receiverParam),
            'from' => $this->address_with0x_prefix($fromParam),
            'kind' => 'sell',
            'partiallyFillable' => false,
            'validTo' => $validTo,
            'sellTokenBalance' => 'erc20',
            'buyTokenBalance' => 'erc20',
        ), $params);
        $quoteResponse = $this->publicPostApiV1Quote ($quoteRequest);
        $quote = $this->safe_dict($quoteResponse, 'quote', $quoteResponse);
        $cowSellAmountRaw = $this->safe_string($quote, 'sellAmount', $sellAmountRaw);
        $cowBuyAmountRaw = $this->safe_string($quote, 'buyAmount');
        $cowFeeRaw = $this->safe_string($quote, 'feeAmount', '0');
        $cowBuyAmount = $this->convert_token_amount($cowBuyAmountRaw, $quoteDecimals);
        $effectiveAmount = $this->convert_token_amount($cowSellAmountRaw, $baseDecimals);
        $cowFee = $this->convert_token_amount($cowFeeRaw, $baseDecimals);
        $cowPrice = null;
        if (($cowBuyAmount !== null) && ($effectiveAmount !== null) && (!Precise::string_eq($effectiveAmount, '0'))) {
            $cowPrice = $this->parse_number(Precise::string_div($cowBuyAmount, $effectiveAmount));
        }
        $comparisons = array();
        for ($i = 0; $i < count($otherExchanges); $i++) {
            $exchange = $otherExchanges[$i];
            $comparison = array(
                'exchange' => null,
                'available' => null,
                'cost' => null,
                'price' => null,
                'slippage' => null,
                'error' => null,
                'info' => null,
            );
            try {
                if ($exchange === null) {
                    continue;
                }
                $comparison['exchange'] = $exchange->id;
                if (($exchange->has !== null) && ($exchange->has['fetchOrderBook'] !== null) && !$exchange->has['fetchOrderBook']) {
                    $comparison['error'] = 'fetchOrderBook not supported';
                    $comparisons[] = $comparison;
                    continue;
                }
                $exchange->loadMarkets ();
                $orderBook = $exchange->fetchOrderBook ($symbol);
                $comparison['info'] = $orderBook;
                $asks = $this->safe_list($orderBook, 'asks', $orderBook['asks']);
                $remaining = $amountString;
                $cost = '0';
                $filled = '0';
                for ($j = 0; $j < count($asks); $j++) {
                    $level = $asks[$j];
                    $price = $this->number_to_string($level[0]);
                    $size = $this->number_to_string($level[1]);
                    if (($price === null) || ($size === null)) {
                        continue;
                    }
                    if (Precise::string_le($remaining, '0')) {
                        break;
                    }
                    $tradeAmount = Precise::string_min($remaining, $size);
                    $cost = Precise::string_add($cost, Precise::string_mul($tradeAmount, $price));
                    $filled = Precise::string_add($filled, $tradeAmount);
                    $remaining = Precise::string_sub($remaining, $tradeAmount);
                }
                if (Precise::string_le($filled, '0')) {
                    $comparison['error'] = 'insufficient liquidity';
                    $comparisons[] = $comparison;
                    continue;
                }
                $filledNumber = $this->parse_number($filled);
                $costNumber = $this->parse_number($cost);
                $priceNumber = null;
                if ($filledNumber !== null && $filledNumber > 0 && $costNumber !== null) {
                    $priceNumber = $costNumber / $filledNumber;
                }
                $slippage = null;
                if (($cowPrice !== null) && ($priceNumber !== null) && ($cowPrice !== 0)) {
                    $slippage = ($priceNumber - $cowPrice) / $cowPrice;
                }
                $comparison = $this->extend($comparison, array(
                    'available' => $filledNumber,
                    'cost' => $costNumber,
                    'price' => $priceNumber,
                    'slippage' => $slippage,
                    'remaining' => $this->parse_number($remaining),
                ));
            } catch (Exception $error) {
                $errorMessage = $this->json($error);
                if ($error instanceof Error) {
                    $errorMessage = $error->message;
                }
                $comparison['error'] = $errorMessage;
            }
            $comparisons[] = $comparison;
        }
        return array(
            'symbol' => $symbol,
            'amount' => $amount,
            'price' => $this->parse_number($cowPrice),
            'buyAmount' => $this->parse_number($cowBuyAmount),
            'sellAmount' => $this->parse_number($effectiveAmount),
            'fee' => $this->parse_number($cowFee),
            'info' => $quoteResponse,
            'comparisons' => $comparisons,
        );
    }

    public function wait_for_order(?string $id, ?string $symbol = null, ?string $status = null, $params = array ()): array {
        /**
         * polls the exchange until an $order reaches a terminal $status
         *
         * @see https://docs.cow.fi/cow-protocol/reference/apis/orderbook
         *
         * @param {string} $id $order $id (UID)
         * @param {string} $symbol unified market $symbol
         * @param {string} [$status] specific $status to wait for (defaults to any terminal $status)
         * @param {array} [$params] extra parameters specific to the exchange API endpoint
         * @param {int} [$params->pollingDelay] delay between polling requests in milliseconds (default 2000)
         * @param {int} [$params->timeout] maximum time to wait in milliseconds (default 60000)
         * @return {array} an [$order structure](https://docs.ccxt.com/#/?$id=$order-structure)
         */
        $this->load_markets();
        $options = $this->safe_value($this->options, 'waitForOrder', array());
        $statuses = $this->safe_value($options, 'statuses', array( 'closed', 'canceled', 'expired', 'rejected' ));
        $targetStatuses = ($status === null) ? $statuses : array( $status );
        $defaultPollingDelay = $this->safe_integer($options, 'pollingDelay', 2000);
        $defaultTimeout = $this->safe_integer($options, 'timeout', 60000);
        $pollingDelay = $this->safe_integer($params, 'pollingDelay', $defaultPollingDelay);
        $timeout = $this->safe_integer($params, 'timeout', $defaultTimeout);
        $fetchParams = $this->omit($params, array( 'pollingDelay', 'timeout' ));
        $deadline = $this->milliseconds() . $timeout;
        // eslint-disable-next-line no-constant-condition
        while (true) {
            $order = $this->fetch_order($id, $symbol, $fetchParams);
            $orderStatus = $this->safe_string($order, 'status');
            if ($this->in_array($orderStatus, $targetStatuses)) {
                return $order;
            }
            if ($this->milliseconds() > $deadline) {
                throw new InvalidOrder($this->id . ' waitForOrder() timed out waiting for $order ' . $id . ' to reach $status ' . implode(',', $targetStatuses));
            }
            $this->sleep($pollingDelay);
        }
    }

    public function handle_errors(?int $httpCode, string $reason, string $url, string $method, array $headers, string $body, $response, $requestHeaders, $requestBody) {
        if ($response === null) {
            return;
        }
        $errorType = $this->safe_string($response, 'errorType');
        if ($errorType !== null) {
            $description = $this->safe_string($response, 'description');
            $feedback = $this->id . ' ' . ($description === null ? $body : $description);
            $errors = array(
                'DuplicatedOrder' => '\\ccxt\\InvalidOrder',
                'OrderAlreadyExists' => '\\ccxt\\InvalidOrder',
                'InvalidOrder' => '\\ccxt\\InvalidOrder',
                'InsufficientFee' => '\\ccxt\\InvalidOrder',
                'InsufficientFunds' => '\\ccxt\\InsufficientFunds',
                'UnknownOrder' => '\\ccxt\\OrderNotFound',
                'OrderNotFound' => '\\ccxt\\OrderNotFound',
                'OrderExpired' => '\\ccxt\\OrderNotFound',
                'InvalidSignature' => '\\ccxt\\AuthenticationError',
                'UnsupportedSellToken' => '\\ccxt\\BadSymbol',
                'UnsupportedBuyToken' => '\\ccxt\\BadSymbol',
                'UnsupportedSigningScheme' => '\\ccxt\\AuthenticationError',
                'InvalidAppData' => '\\ccxt\\BadRequest',
                'SellAmountDoesNotCoverFee' => '\\ccxt\\InvalidOrder',
                'SlippageTooLarge' => '\\ccxt\\InvalidOrder',
                'NoLiquidity' => '\\ccxt\\InvalidOrder',
            );
            $Exception = $this->safe_value($errors, $errorType, '\\ccxt\\ExchangeError');
            throw new $Exception($feedback);
        }
        $errorsList = $this->safe_list($response, 'errors');
        if ($errorsList !== null) {
            for ($i = 0; $i < count($errorsList); $i++) {
                $error = $errorsList[$i];
                $type = $this->safe_string($error, 'errorType');
                if ($type !== null) {
                    $description = $this->safe_string($error, 'description');
                    $feedback = $this->id . ' ' . ($description === null ? $this->json($error) : $description);
                    $errors = array(
                        'DuplicatedOrder' => '\\ccxt\\InvalidOrder',
                        'InvalidOrder' => '\\ccxt\\InvalidOrder',
                        'InsufficientFee' => '\\ccxt\\InvalidOrder',
                        'InsufficientFunds' => '\\ccxt\\InsufficientFunds',
                        'UnsupportedSellToken' => '\\ccxt\\BadSymbol',
                        'UnsupportedBuyToken' => '\\ccxt\\BadSymbol',
                        'NoLiquidity' => '\\ccxt\\InvalidOrder',
                    );
                    $Exception = $this->safe_value($errors, $type, '\\ccxt\\ExchangeError');
                    throw new $Exception($feedback);
                }
            }
        }
        $status = $this->safe_string($response, 'status');
        if ($status !== null) {
            $knownOrderStatuses = array( 'open', 'pending', 'pending-solver-submission', 'presignatureAwaiting', 'presignaturePending', 'fulfilled', 'expired', 'solved', 'cancelled', 'canceled', 'retracted', 'failed' );
            if (!$this->in_array($status, $knownOrderStatuses)) {
                if (($status !== 'success') && ($status !== 'ok')) {
                    $description = $this->safe_string($response, 'description');
                    $feedback = $this->id . ' ' . ($description === null ? $body : $description);
                    throw new ExchangeError($feedback);
                }
            }
        }
    }
}
